/*
 * Copyright (c) 2017, Adam <Adam@sigterm.info>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package net.runelite.api.widgets;

/**
 * Represents a group-child {@link Widget} relationship.
 * <p>
 * For getting a specific widget from the client, see {@link net.runelite.api.Client#getWidget(WidgetInfo)}.
 */
public enum WidgetInfo
{
	FAIRY_RING_TELEPORT_BUTTON(ComponentID.FAIRY_RING_TELEPORT_BUTTON),

	WORLD_SWITCHER_BUTTON(ComponentID.LOGOUT_PANEL_WORLD_SWITCHER_BUTTON),
	LOGOUT_BUTTON(ComponentID.LOGOUT_PANEL_LOGOUT_BUTTON),

	INVENTORY(WidgetID.INVENTORY_GROUP_ID, 0),
	FRIENDS_LIST(WidgetID.FRIENDS_LIST_GROUP_ID, 0),
	IGNORE_LIST(WidgetID.IGNORE_LIST_GROUP_ID, 0),
	FRIENDS_CHAT(WidgetID.FRIENDS_CHAT_GROUP_ID, 0),
	RAIDING_PARTY(WidgetID.RAIDING_PARTY_GROUP_ID, 0),

	WORLD_MAP_VIEW(ComponentID.WORLD_MAP_MAPVIEW),
	WORLD_MAP_OVERVIEW_MAP(ComponentID.WORLD_MAP_OVERVIEW_MAP),
	WORLD_MAP_BOTTOM_BAR(ComponentID.WORLD_MAP_BOTTOM_BAR),
	WORLD_MAP_SEARCH(ComponentID.WORLD_MAP_SEARCH),
	WORLD_MAP_SURFACE_SELECTOR(ComponentID.WORLD_MAP_SURFACE_SELECTOR),
	WORLD_MAP_TOOLTIP(ComponentID.WORLD_MAP_TOOLTIP),

	CLUE_SCROLL_TEXT(ComponentID.CLUESCROLL_TEXT),
	CLUE_SCROLL_REWARD_ITEM_CONTAINER(ComponentID.CLUESCROLL_REWARD_ITEM_CONTAINER),

	EQUIPMENT(WidgetID.EQUIPMENT_GROUP_ID, 0),
	EQUIPMENT_INVENTORY_ITEMS_CONTAINER(ComponentID.EQUIPMENT_INVENTORY_ITEM_CONTAINER),

	EMOTE_WINDOW(ComponentID.EMOTES_WINDOW),
	EMOTE_SCROLL_CONTAINER(ComponentID.EMOTES_EMOTE_SCROLL_CONTAINER),
	EMOTE_CONTAINER(ComponentID.EMOTES_EMOTE_CONTAINER),
	EMOTE_SCROLLBAR(ComponentID.EMOTES_EMOTE_SCROLLBAR),

	MUSIC_WINDOW(ComponentID.MUSIC_CONTAINER),
	MUSIC_TRACK_LIST(ComponentID.MUSIC_LIST),
	MUSIC_TRACK_SCROLL_CONTAINER(ComponentID.MUSIC_SCROLL_CONTAINER),
	MUSIC_TRACK_SCROLLBAR(ComponentID.MUSIC_SCROLLBAR),

	DIARY_QUEST_WIDGET_TITLE(ComponentID.DIARY_TITLE),
	DIARY_QUEST_WIDGET_TEXT(ComponentID.DIARY_TEXT),

	ACHIEVEMENT_DIARY_SCROLL_TITLE(ComponentID.ACHIEVEMENT_DIARY_SCROLL_TITLE),
	ACHIEVEMENT_DIARY_SCROLL_TEXT(ComponentID.ACHIEVEMENT_DIARY_SCROLL_TEXT),

	PEST_CONTROL_BOAT_INFO(WidgetID.PEST_CONTROL_BOAT_GROUP_ID, 2),
	PEST_CONTROL_KNIGHT_INFO_CONTAINER(ComponentID.PEST_CONTROL_KNIGHT_INFO_CONTAINER),
	PEST_CONTROL_ACTIVITY_SHIELD_INFO_CONTAINER(ComponentID.PEST_CONTROL_ACTIVITY_SHIELD_CONTAINER),
	PEST_CONTROL_PURPLE_SHIELD(ComponentID.PEST_CONTROL_PURPLE_SHIELD),
	PEST_CONTROL_BLUE_SHIELD(ComponentID.PEST_CONTROL_BLUE_SHIELD),
	PEST_CONTROL_YELLOW_SHIELD(ComponentID.PEST_CONTROL_YELLOW_SHIELD),
	PEST_CONTROL_RED_SHIELD(ComponentID.PEST_CONTROL_RED_SHIELD),
	PEST_CONTROL_PURPLE_HEALTH(ComponentID.PEST_CONTROL_PURPLE_HEALTH),
	PEST_CONTROL_BLUE_HEALTH(ComponentID.PEST_CONTROL_BLUE_HEALTH),
	PEST_CONTROL_YELLOW_HEALTH(ComponentID.PEST_CONTROL_YELLOW_HEALTH),
	PEST_CONTROL_RED_HEALTH(ComponentID.PEST_CONTROL_RED_HEALTH),
	PEST_CONTROL_PURPLE_ICON(ComponentID.PEST_CONTROL_PURPLE_ICON),
	PEST_CONTROL_BLUE_ICON(ComponentID.PEST_CONTROL_BLUE_ICON),
	PEST_CONTROL_YELLOW_ICON(ComponentID.PEST_CONTROL_YELLOW_ICON),
	PEST_CONTROL_RED_ICON(ComponentID.PEST_CONTROL_RED_ICON),
	PEST_CONTROL_ACTIVITY_BAR(ComponentID.PEST_CONTROL_ACTIVITY_BAR),
	PEST_CONTROL_ACTIVITY_PROGRESS(ComponentID.PEST_CONTROL_ACTIVITY_PROGRESS),

	VOLCANIC_MINE_TIME_LEFT(ComponentID.VOLCANIC_MINE_TIME_LEFT),
	VOLCANIC_MINE_POINTS(ComponentID.VOLCANIC_MINE_POINTS),
	VOLCANIC_MINE_STABILITY(ComponentID.VOLCANIC_MINE_STABILITY),
	VOLCANIC_MINE_PLAYER_COUNT(ComponentID.VOLCANIC_MINE_PLAYER_COUNT),
	VOLCANIC_MINE_VENTS_INFOBOX_GROUP(ComponentID.VOLCANIC_MINE_VENTS_INFOBOX_CONTAINER),
	VOLCANIC_MINE_STABILITY_INFOBOX_GROUP(ComponentID.VOLCANIC_MINE_STABILITY_INFOBOX_CONTAINER),
	VOLCANIC_MINE_VENT_A_PERCENTAGE(ComponentID.VOLCANIC_MINE_VENT_A_PERCENTAGE),
	VOLCANIC_MINE_VENT_B_PERCENTAGE(ComponentID.VOLCANIC_MINE_VENT_B_PERCENTAGE),
	VOLCANIC_MINE_VENT_C_PERCENTAGE(ComponentID.VOLCANIC_MINE_VENT_C_PERCENTAGE),
	VOLCANIC_MINE_VENT_A_STATUS(ComponentID.VOLCANIC_MINE_VENT_A_STATUS),
	VOLCANIC_MINE_VENT_B_STATUS(ComponentID.VOLCANIC_MINE_VENT_B_STATUS),
	VOLCANIC_MINE_VENT_C_STATUS(ComponentID.VOLCANIC_MINE_VENT_C_STATUS),

	FRIEND_CHAT_TITLE(ComponentID.FRIEND_LIST_TITLE),
	FRIEND_LIST_FULL_CONTAINER(ComponentID.FRIEND_LIST_FULL_CONTAINER),
	FRIEND_LIST_SORT_BY_NAME_BUTTON(ComponentID.FRIEND_LIST_SORT_BY_NAME_BUTTON),
	FRIEND_LIST_SORT_BY_LAST_WORLD_CHANGE_BUTTON(ComponentID.FRIEND_LIST_SORT_BY_LAST_WORLD_CHANGE_BUTTON),
	FRIEND_LIST_SORT_BY_WORLD_BUTTON(ComponentID.FRIEND_LIST_SORT_BY_WORLD_BUTTON),
	FRIEND_LIST_LEGACY_SORT_BUTTON(ComponentID.FRIEND_LIST_LEGACY_SORT_BUTTON),
	FRIEND_LIST_NAMES_CONTAINER(ComponentID.FRIEND_LIST_NAMES_CONTAINER),
	FRIEND_LIST_SCROLL_BAR(ComponentID.FRIEND_LIST_SCROLL_BAR),
	FRIEND_LIST_LOADING_TEXT(ComponentID.FRIEND_LIST_LOADING_TEXT),
	FRIEND_LIST_PREVIOUS_NAME_HOLDER(ComponentID.FRIEND_LIST_PREVIOUS_NAME_HOLDER),

	IGNORE_TITLE(ComponentID.IGNORE_LIST_TITLE),
	IGNORE_FULL_CONTAINER(ComponentID.IGNORE_LIST_FULL_CONTAINER),
	IGNORE_SORT_BY_NAME_BUTTON(ComponentID.IGNORE_LIST_SORT_BY_NAME_BUTTON),
	IGNORE_LEGACY_SORT_BUTTON(ComponentID.IGNORE_LIST_LEGACY_SORT_BUTTON),
	IGNORE_NAMES_CONTAINER(ComponentID.IGNORE_LIST_NAMES_CONTAINER),
	IGNORE_SCROLL_BAR(ComponentID.IGNORE_LIST_SCROLL_BAR),
	IGNORE_LOADING_TEXT(ComponentID.IGNORE_LIST_LOADING_TEXT),
	IGNORE_PREVIOUS_NAME_HOLDER(ComponentID.IGNORE_LIST_PREVIOUS_NAME_HOLDER),

	EXPLORERS_RING_ALCH_INVENTORY(ComponentID.EXPLORERS_RING_INVENTORY),

	FRIENDS_CHAT_ROOT(ComponentID.FRIENDS_CHAT_ROOT),
	FRIENDS_CHAT_TITLE(ComponentID.FRIENDS_CHAT_TITLE),
	FRIENDS_CHAT_OWNER(ComponentID.FRIENDS_CHAT_OWNER),
	FRIENDS_CHAT_LIST(ComponentID.FRIENDS_CHAT_LIST),

	BANK_CONTAINER(ComponentID.BANK_CONTAINER),
	BANK_SEARCH_BUTTON_BACKGROUND(ComponentID.BANK_SEARCH_BUTTON_BACKGROUND),
	BANK_ITEM_CONTAINER(ComponentID.BANK_ITEM_CONTAINER),
	BANK_INVENTORY_ITEMS_CONTAINER(ComponentID.BANK_INVENTORY_ITEM_CONTAINER),
	BANK_EQUIPMENT_INVENTORY_ITEMS_CONTAINER(ComponentID.BANK_INVENTORY_EQUIPMENT_ITEM_CONTAINER),
	BANK_TITLE_BAR(ComponentID.BANK_TITLE_BAR),
	BANK_INCINERATOR(ComponentID.BANK_INCINERATOR),
	BANK_INCINERATOR_CONFIRM(ComponentID.BANK_INCINERATOR_CONFIRM),
	BANK_CONTENT_CONTAINER(ComponentID.BANK_CONTENT_CONTAINER),
	BANK_DEPOSIT_EQUIPMENT(ComponentID.BANK_DEPOSIT_EQUIPMENT),
	BANK_DEPOSIT_INVENTORY(ComponentID.BANK_DEPOSIT_INVENTORY),
	BANK_TAB_CONTAINER(ComponentID.BANK_TAB_CONTAINER),
	BANK_EQUIPMENT_CONTAINER(ComponentID.BANK_EQUIPMENT_PARENT),
	BANK_EQUIPMENT_BUTTON(ComponentID.BANK_EQUIPMENT_BUTTON),
	BANK_POPUP(ComponentID.BANK_POPUP),
	BANK_ITEM_COUNT_TOP(ComponentID.BANK_ITEM_COUNT_TOP),
	BANK_ITEM_COUNT_BAR(ComponentID.BANK_ITEM_COUNT_BAR),
	BANK_ITEM_COUNT_BOTTOM(ComponentID.BANK_ITEM_COUNT_BOTTOM),
	BANK_GROUP_STORAGE_BUTTON(ComponentID.BANK_GROUP_STORAGE_BUTTON),
	BANK_SCROLLBAR(ComponentID.BANK_SCROLLBAR),
	BANK_PIN_CONTAINER(ComponentID.BANK_PIN_CONTAINER),
	BANK_SETTINGS_BUTTON(ComponentID.BANK_SETTINGS_BUTTON),
	BANK_TUTORIAL_BUTTON(ComponentID.BANK_TUTORIAL_BUTTON),

	GROUP_STORAGE_UI(ComponentID.GROUP_STORAGE_UI),
	GROUP_STORAGE_ITEM_CONTAINER(ComponentID.GROUP_STORAGE_ITEM_CONTAINER),

	GRAND_EXCHANGE_WINDOW_CONTAINER(ComponentID.GRAND_EXCHANGE_WINDOW_CONTAINER),
	GRAND_EXCHANGE_OFFER_CONTAINER(ComponentID.GRAND_EXCHANGE_OFFER_CONTAINER),
	GRAND_EXCHANGE_OFFER_TEXT(ComponentID.GRAND_EXCHANGE_OFFER_DESCRIPTION),

	GRAND_EXCHANGE_INVENTORY_ITEMS_CONTAINER(ComponentID.GRAND_EXCHANGE_INVENTORY_INVENTORY_ITEM_CONTAINER),

	DEPOSIT_BOX_INVENTORY_ITEMS_CONTAINER(ComponentID.DEPOSIT_BOX_INVENTORY_ITEM_CONTAINER),

	SHOP_INVENTORY_ITEMS_CONTAINER(ComponentID.SHOP_INVENTORY_ITEM_CONTAINER),

	SMITHING_INVENTORY_ITEMS_CONTAINER(ComponentID.SMITHING_INVENTORY_ITEM_CONTAINER),

	GUIDE_PRICES_ITEMS_CONTAINER(ComponentID.GUIDE_PRICES_ITEM_CONTAINER),
	GUIDE_PRICES_INVENTORY_ITEMS_CONTAINER(ComponentID.GUIDE_PRICES_INVENTORY_ITEM_CONTAINER),

	RUNE_POUCH_ITEM_CONTAINER(WidgetID.RUNE_POUCH_GROUP_ID, 0),

	MINIMAP_ORBS(WidgetID.MINIMAP_GROUP_ID, 0),
	MINIMAP_XP_ORB(ComponentID.MINIMAP_XP_ORB),
	MINIMAP_PRAYER_ORB(ComponentID.MINIMAP_PRAYER_ORB),
	MINIMAP_QUICK_PRAYER_ORB(ComponentID.MINIMAP_QUICK_PRAYER_ORB),
	MINIMAP_PRAYER_ORB_TEXT(ComponentID.MINIMAP_PRAYER_ORB_TEXT),
	MINIMAP_RUN_ORB(ComponentID.MINIMAP_RUN_ORB),
	MINIMAP_TOGGLE_RUN_ORB(ComponentID.MINIMAP_TOGGLE_RUN_ORB),
	MINIMAP_RUN_ORB_TEXT(ComponentID.MINIMAP_RUN_ORB_TEXT),
	MINIMAP_HEALTH_ORB(ComponentID.MINIMAP_HEALTH_ORB),
	MINIMAP_SPEC_ORB(ComponentID.MINIMAP_SPEC_ORB),
	MINIMAP_WORLDMAP_ORB(ComponentID.MINIMAP_WORLDMAP_ORB),
	MINIMAP_WIKI_BANNER_PARENT(ComponentID.MINIMAP_WIKI_BANNER_PARENT),
	MINIMAP_WIKI_BANNER(ComponentID.MINIMAP_WIKI_BANNER),
	MINIMAP_WORLDMAP_OPTIONS(ComponentID.MINIMAP_WORLDMAP_OPTIONS),

	LMS_INFO(ComponentID.LMS_INFO),
	LMS_KDA(ComponentID.LMS_INGAME_INFO),

	LOGIN_CLICK_TO_PLAY_SCREEN(WidgetID.LOGIN_CLICK_TO_PLAY_GROUP_ID, 0),
	LOGIN_CLICK_TO_PLAY_SCREEN_MESSAGE_OF_THE_DAY(ComponentID.LOGIN_CLICK_TO_PLAY_SCREEN_MESSAGE_OF_THE_DAY),

	FIXED_VIEWPORT(ComponentID.FIXED_VIEWPORT_FIXED_VIEWPORT),
	FIXED_VIEWPORT_ROOT_INTERFACE_CONTAINER(ComponentID.FIXED_VIEWPORT_ROOT_INTERFACE_CONTAINER),
	FIXED_VIEWPORT_BANK_CONTAINER(ComponentID.FIXED_VIEWPORT_BANK_CONTAINER),
	FIXED_VIEWPORT_INTERFACE_CONTAINER(ComponentID.FIXED_VIEWPORT_INTERFACE_CONTAINER),
	FIXED_VIEWPORT_INVENTORY_CONTAINER(ComponentID.FIXED_VIEWPORT_INVENTORY_CONTAINER),
	FIXED_VIEWPORT_COMBAT_TAB(ComponentID.FIXED_VIEWPORT_COMBAT_TAB),
	FIXED_VIEWPORT_STATS_TAB(ComponentID.FIXED_VIEWPORT_STATS_TAB),
	FIXED_VIEWPORT_QUESTS_TAB(ComponentID.FIXED_VIEWPORT_QUESTS_TAB),
	FIXED_VIEWPORT_INVENTORY_TAB(ComponentID.FIXED_VIEWPORT_INVENTORY_TAB),
	FIXED_VIEWPORT_EQUIPMENT_TAB(ComponentID.FIXED_VIEWPORT_EQUIPMENT_TAB),
	FIXED_VIEWPORT_PRAYER_TAB(ComponentID.FIXED_VIEWPORT_PRAYER_TAB),
	FIXED_VIEWPORT_MAGIC_TAB(ComponentID.FIXED_VIEWPORT_MAGIC_TAB),
	FIXED_VIEWPORT_FRIENDS_CHAT_TAB(ComponentID.FIXED_VIEWPORT_FRIENDS_CHAT_TAB),
	FIXED_VIEWPORT_FRIENDS_TAB(ComponentID.FIXED_VIEWPORT_FRIENDS_TAB),
	FIXED_VIEWPORT_IGNORES_TAB(ComponentID.FIXED_VIEWPORT_IGNORES_TAB),
	FIXED_VIEWPORT_LOGOUT_TAB(ComponentID.FIXED_VIEWPORT_LOGOUT_TAB),
	FIXED_VIEWPORT_OPTIONS_TAB(ComponentID.FIXED_VIEWPORT_OPTIONS_TAB),
	FIXED_VIEWPORT_EMOTES_TAB(ComponentID.FIXED_VIEWPORT_EMOTES_TAB),
	FIXED_VIEWPORT_MUSIC_TAB(ComponentID.FIXED_VIEWPORT_MUSIC_TAB),
	FIXED_VIEWPORT_COMBAT_ICON(ComponentID.FIXED_VIEWPORT_COMBAT_ICON),
	FIXED_VIEWPORT_STATS_ICON(ComponentID.FIXED_VIEWPORT_STATS_ICON),
	FIXED_VIEWPORT_QUESTS_ICON(ComponentID.FIXED_VIEWPORT_QUESTS_ICON),
	FIXED_VIEWPORT_INVENTORY_ICON(ComponentID.FIXED_VIEWPORT_INVENTORY_ICON),
	FIXED_VIEWPORT_EQUIPMENT_ICON(ComponentID.FIXED_VIEWPORT_EQUIPMENT_ICON),
	FIXED_VIEWPORT_PRAYER_ICON(ComponentID.FIXED_VIEWPORT_PRAYER_ICON),
	FIXED_VIEWPORT_MAGIC_ICON(ComponentID.FIXED_VIEWPORT_MAGIC_ICON),
	FIXED_VIEWPORT_FRIENDS_CHAT_ICON(ComponentID.FIXED_VIEWPORT_FRIENDS_CHAT_ICON),
	FIXED_VIEWPORT_FRIENDS_ICON(ComponentID.FIXED_VIEWPORT_FRIENDS_ICON),
	FIXED_VIEWPORT_IGNORES_ICON(ComponentID.FIXED_VIEWPORT_IGNORES_ICON),
	FIXED_VIEWPORT_LOGOUT_ICON(ComponentID.FIXED_VIEWPORT_LOGOUT_ICON),
	FIXED_VIEWPORT_OPTIONS_ICON(ComponentID.FIXED_VIEWPORT_OPTIONS_ICON),
	FIXED_VIEWPORT_EMOTES_ICON(ComponentID.FIXED_VIEWPORT_EMOTES_ICON),
	FIXED_VIEWPORT_MUSIC_ICON(ComponentID.FIXED_VIEWPORT_MUSIC_ICON),
	FIXED_VIEWPORT_MINIMAP(ComponentID.FIXED_VIEWPORT_MINIMAP),
	FIXED_VIEWPORT_MINIMAP_DRAW_AREA(ComponentID.FIXED_VIEWPORT_MINIMAP_DRAW_AREA),

	RESIZABLE_MINIMAP_STONES_WIDGET(ComponentID.RESIZABLE_VIEWPORT_MINIMAP),
	RESIZABLE_MINIMAP_STONES_DRAW_AREA(ComponentID.RESIZABLE_VIEWPORT_MINIMAP_DRAW_AREA),
	RESIZABLE_MINIMAP_STONES_ORB_HOLDER(ComponentID.RESIZABLE_VIEWPORT_MINIMAP_ORB_HOLDER),
	RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX(ComponentID.RESIZABLE_VIEWPORT_RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX),
	RESIZABLE_VIEWPORT_COMBAT_TAB(ComponentID.RESIZABLE_VIEWPORT_COMBAT_TAB),
	RESIZABLE_VIEWPORT_STATS_TAB(ComponentID.RESIZABLE_VIEWPORT_STATS_TAB),
	RESIZABLE_VIEWPORT_QUESTS_TAB(ComponentID.RESIZABLE_VIEWPORT_QUESTS_TAB),
	RESIZABLE_VIEWPORT_INVENTORY_TAB(ComponentID.RESIZABLE_VIEWPORT_INVENTORY_TAB),
	RESIZABLE_VIEWPORT_EQUIPMENT_TAB(ComponentID.RESIZABLE_VIEWPORT_EQUIPMENT_TAB),
	RESIZABLE_VIEWPORT_PRAYER_TAB(ComponentID.RESIZABLE_VIEWPORT_PRAYER_TAB),
	RESIZABLE_VIEWPORT_MAGIC_TAB(ComponentID.RESIZABLE_VIEWPORT_MAGIC_TAB),
	RESIZABLE_VIEWPORT_FRIENDS_CHAT_TAB(ComponentID.RESIZABLE_VIEWPORT_FRIENDS_CHAT_TAB),
	RESIZABLE_VIEWPORT_FRIENDS_TAB(ComponentID.RESIZABLE_VIEWPORT_FRIENDS_TAB),
	RESIZABLE_VIEWPORT_IGNORES_TAB(ComponentID.RESIZABLE_VIEWPORT_IGNORES_TAB),
	RESIZABLE_VIEWPORT_LOGOUT_TAB(ComponentID.RESIZABLE_VIEWPORT_LOGOUT_TAB),
	RESIZABLE_VIEWPORT_OPTIONS_TAB(ComponentID.RESIZABLE_VIEWPORT_OPTIONS_TAB),
	RESIZABLE_VIEWPORT_EMOTES_TAB(ComponentID.RESIZABLE_VIEWPORT_EMOTES_TAB),
	RESIZABLE_VIEWPORT_MUSIC_TAB(ComponentID.RESIZABLE_VIEWPORT_MUSIC_TAB),
	RESIZABLE_VIEWPORT_COMBAT_ICON(ComponentID.RESIZABLE_VIEWPORT_COMBAT_ICON),
	RESIZABLE_VIEWPORT_STATS_ICON(ComponentID.RESIZABLE_VIEWPORT_STATS_ICON),
	RESIZABLE_VIEWPORT_QUESTS_ICON(ComponentID.RESIZABLE_VIEWPORT_QUESTS_ICON),
	RESIZABLE_VIEWPORT_INVENTORY_ICON(ComponentID.RESIZABLE_VIEWPORT_INVENTORY_ICON),
	RESIZABLE_VIEWPORT_EQUIPMENT_ICON(ComponentID.RESIZABLE_VIEWPORT_EQUIPMENT_ICON),
	RESIZABLE_VIEWPORT_PRAYER_ICON(ComponentID.RESIZABLE_VIEWPORT_PRAYER_ICON),
	RESIZABLE_VIEWPORT_MAGIC_ICON(ComponentID.RESIZABLE_VIEWPORT_MAGIC_ICON),
	RESIZABLE_VIEWPORT_FRIENDS_CHAT_ICON(ComponentID.RESIZABLE_VIEWPORT_FRIENDS_CHAT_ICON),
	RESIZABLE_VIEWPORT_FRIENDS_ICON(ComponentID.RESIZABLE_VIEWPORT_FRIENDS_ICON),
	RESIZABLE_VIEWPORT_IGNORES_ICON(ComponentID.RESIZABLE_VIEWPORT_IGNORES_ICON),
	RESIZABLE_VIEWPORT_LOGOUT_ICON(ComponentID.RESIZABLE_VIEWPORT_LOGOUT_ICON),
	RESIZABLE_VIEWPORT_OPTIONS_ICON(ComponentID.RESIZABLE_VIEWPORT_OPTIONS_ICON),
	RESIZABLE_VIEWPORT_EMOTES_ICON(ComponentID.RESIZABLE_VIEWPORT_EMOTES_ICON),
	RESIZABLE_VIEWPORT_MUSIC_ICON(ComponentID.RESIZABLE_VIEWPORT_MUSIC_ICON),
	RESIZABLE_VIEWPORT_INTERFACE_CONTAINER(ComponentID.RESIZABLE_VIEWPORT_INTERFACE_CONTAINER),
	RESIZABLE_VIEWPORT_INVENTORY_CONTAINER(ComponentID.RESIZABLE_VIEWPORT_INVENTORY_CONTAINER),
	RESIZABLE_VIEWPORT_CHATBOX_PARENT(ComponentID.RESIZABLE_VIEWPORT_CHATBOX_PARENT),
	RESIZABLE_VIEWPORT_INVENTORY_PARENT(ComponentID.RESIZABLE_VIEWPORT_INVENTORY_PARENT),

	RESIZABLE_MINIMAP_WIDGET(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_MINIMAP),
	RESIZABLE_MINIMAP_DRAW_AREA(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_MINIMAP_DRAW_AREA),
	RESIZABLE_MINIMAP_ORB_HOLDER(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_MINIMAP_ORB_HOLDER),
	RESIZABLE_MINIMAP_LOGOUT_BUTTON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_MINIMAP_LOGOUT_BUTTON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_RESIZABLE_VIEWPORT_BOTTOM_LINE),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_LOGOUT_BUTTON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_LOGOUT_BUTTON_OVERLAY),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_QUESTS_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_QUESTS_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_TAB(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_PRAYER_TAB(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_PRAYER_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_PRAYER_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_PRAYER_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_EQUIPMENT_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_EQUIP_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_COMBAT_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_CMB_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_STATS_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_SKILLS_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_MAGIC_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_MAGIC_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_FRIEND_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_FRIEND_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_FRIEND_CHAT_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_FC_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_OPTIONS_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_SETTINGS_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_EMOTES_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_EMOTE_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_MUSIC_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_MUSIC_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_CONTAINER(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_CONTAINER),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INTERFACE_CONTAINER(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_INTERFACE_CONTAINER),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_CHATBOX_PARENT(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_CHATBOX_PARENT),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_TABS1(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_TABS1),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_TABS2(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_TABS2),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_PARENT(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_PARENT),

	COMBAT_LEVEL(ComponentID.COMBAT_LEVEL),
	COMBAT_STYLE_ONE(ComponentID.COMBAT_STYLE_ONE),
	COMBAT_STYLE_TWO(ComponentID.COMBAT_STYLE_TWO),
	COMBAT_STYLE_THREE(ComponentID.COMBAT_STYLE_THREE),
	COMBAT_STYLE_FOUR(ComponentID.COMBAT_STYLE_FOUR),
	COMBAT_SPELLS(ComponentID.COMBAT_SPELLS),
	COMBAT_DEFENSIVE_SPELL_BOX(ComponentID.COMBAT_DEFENSIVE_SPELL_BOX),
	COMBAT_DEFENSIVE_SPELL_ICON(ComponentID.COMBAT_DEFENSIVE_SPELL_ICON),
	COMBAT_DEFENSIVE_SPELL_SHIELD(ComponentID.COMBAT_DEFENSIVE_SPELL_SHIELD),
	COMBAT_DEFENSIVE_SPELL_TEXT(ComponentID.COMBAT_DEFENSIVE_SPELL_TEXT),
	COMBAT_SPELL_BOX(ComponentID.COMBAT_SPELL_BOX),
	COMBAT_SPELL_ICON(ComponentID.COMBAT_SPELL_ICON),
	COMBAT_SPELL_TEXT(ComponentID.COMBAT_SPELL_TEXT),
	COMBAT_AUTO_RETALIATE(ComponentID.COMBAT_AUTO_RETALIATE),

	DIALOG_OPTION(WidgetID.DIALOG_OPTION_GROUP_ID, 0),
	DIALOG_OPTION_OPTIONS(ComponentID.DIALOG_OPTION_OPTIONS),

	DIALOG_SPRITE(WidgetID.DIALOG_SPRITE_GROUP_ID, 0),
	DIALOG_SPRITE_SPRITE(ComponentID.DIALOG_SPRITE_SPRITE),
	DIALOG_SPRITE_TEXT(ComponentID.DIALOG_SPRITE_TEXT),
	DIALOG_DOUBLE_SPRITE_TEXT(ComponentID.DIALOG_DOUBLE_SPRITE_TEXT),
	DIALOG_DOUBLE_SPRITE_SPRITE1(ComponentID.DIALOG_DOUBLE_SPRITE_SPRITE1),
	DIALOG_DOUBLE_SPRITE_SPRITE2(ComponentID.DIALOG_DOUBLE_SPRITE_SPRITE2),

	DIALOG_NPC_NAME(ComponentID.DIALOG_NPC_NAME),
	DIALOG_NPC_TEXT(ComponentID.DIALOG_NPC_TEXT),
	DIALOG_NPC_HEAD_MODEL(ComponentID.DIALOG_NPC_HEAD_MODEL),

	DIALOG_PLAYER(WidgetID.DIALOG_PLAYER_GROUP_ID, 0),
	DIALOG_PLAYER_TEXT(ComponentID.DIALOG_PLAYER_TEXT),

	PRIVATE_CHAT_MESSAGE(WidgetID.PRIVATE_CHAT, 0),

	SLAYER_REWARDS_TOPBAR(ComponentID.SLAYER_REWARDS_TOP_BAR),

	CHATBOX_PARENT(ComponentID.CHATBOX_PARENT),
	CHATBOX(ComponentID.CHATBOX_FRAME),
	CHATBOX_MESSAGES(ComponentID.CHATBOX_MESSAGES),
	CHATBOX_BUTTONS(ComponentID.CHATBOX_BUTTONS),
	CHATBOX_TITLE(ComponentID.CHATBOX_TITLE),
	CHATBOX_FULL_INPUT(ComponentID.CHATBOX_FULL_INPUT),
	CHATBOX_GE_SEARCH_RESULTS(ComponentID.CHATBOX_GE_SEARCH_RESULTS),
	CHATBOX_CONTAINER(ComponentID.CHATBOX_CONTAINER),
	CHATBOX_REPORT_TEXT(ComponentID.CHATBOX_REPORT_TEXT),
	CHATBOX_INPUT(ComponentID.CHATBOX_INPUT),
	CHATBOX_TRANSPARENT_BACKGROUND(ComponentID.CHATBOX_TRANSPARENT_BACKGROUND),
	CHATBOX_TRANSPARENT_LINES(ComponentID.CHATBOX_TRANSPARENT_BACKGROUND_LINES),
	CHATBOX_MESSAGE_LINES(ComponentID.CHATBOX_MESSAGE_LINES),
	CHATBOX_FIRST_MESSAGE(ComponentID.CHATBOX_FIRST_MESSAGE),
	CHATBOX_TAB_ALL(ComponentID.CHATBOX_TAB_ALL),
	CHATBOX_TAB_GAME(ComponentID.CHATBOX_TAB_GAME),
	CHATBOX_TAB_PUBLIC(ComponentID.CHATBOX_TAB_PUBLIC),
	CHATBOX_TAB_PRIVATE(ComponentID.CHATBOX_TAB_PRIVATE),
	CHATBOX_TAB_CHANNEL(ComponentID.CHATBOX_TAB_CHANNEL),
	CHATBOX_TAB_CLAN(ComponentID.CHATBOX_TAB_CLAN),
	CHATBOX_TAB_TRADE(ComponentID.CHATBOX_TAB_TRADE),

	BA_TEAM(ComponentID.BA_TEAM_TEAM),

	BA_HEAL_ROLE_TEXT(ComponentID.BA_HEALER_ROLE),
	BA_HEAL_ROLE_SPRITE(ComponentID.BA_HEALER_ROLE_SPRITE),

	BA_HEAL_TEAMMATES(ComponentID.BA_HEALER_TEAMMATES),
	BA_HEAL_TEAMMATE1(ComponentID.BA_HEALER_TEAMMATE1),
	BA_HEAL_TEAMMATE2(ComponentID.BA_HEALER_TEAMMATE2),
	BA_HEAL_TEAMMATE3(ComponentID.BA_HEALER_TEAMMATE3),
	BA_HEAL_TEAMMATE4(ComponentID.BA_HEALER_TEAMMATE4),

	BA_COLL_ROLE_TEXT(ComponentID.BA_COLLECTOR_ROLE),
	BA_COLL_ROLE_SPRITE(ComponentID.BA_COLLECTOR_ROLE_SPRITE),

	BA_ATK_ROLE_TEXT(ComponentID.BA_ATTACKER_ROLE),
	BA_ATK_ROLE_SPRITE(ComponentID.BA_ATTACKER_ROLE_SPRITE),

	BA_DEF_ROLE_TEXT(ComponentID.BA_DEFENDER_ROLE),
	BA_DEF_ROLE_SPRITE(ComponentID.BA_DEFENDER_ROLE_SPRITE),

	BA_REWARD_TEXT(ComponentID.BA_REWARD_REWARD_TEXT),

	LEVEL_UP(WidgetID.LEVEL_UP_GROUP_ID, 0),
	LEVEL_UP_SKILL(ComponentID.LEVEL_UP_SKILL),
	LEVEL_UP_LEVEL(ComponentID.LEVEL_UP_LEVEL),

	QUEST_COMPLETED(WidgetID.QUEST_COMPLETED_GROUP_ID, 0),
	QUEST_COMPLETED_NAME_TEXT(ComponentID.QUEST_COMPLETED_NAME_TEXT),

	MOTHERLODE_MINE(WidgetID.MOTHERLODE_MINE_GROUP_ID, 0),

	GWD_KC(WidgetID.GWD_KC_GROUP_ID, 5),

	PUZZLE_BOX(ComponentID.PUZZLE_BOX_VISIBLE_BOX),

	LIGHT_BOX(ComponentID.LIGHT_BOX_LIGHT_BOX),
	LIGHT_BOX_CONTENTS(ComponentID.LIGHT_BOX_LIGHT_BULB_CONTAINER),
	LIGHT_BOX_BUTTON_A(ComponentID.LIGHT_BOX_BUTTON_A),
	LIGHT_BOX_BUTTON_B(ComponentID.LIGHT_BOX_BUTTON_B),
	LIGHT_BOX_BUTTON_C(ComponentID.LIGHT_BOX_BUTTON_C),
	LIGHT_BOX_BUTTON_D(ComponentID.LIGHT_BOX_BUTTON_D),
	LIGHT_BOX_BUTTON_E(ComponentID.LIGHT_BOX_BUTTON_E),
	LIGHT_BOX_BUTTON_F(ComponentID.LIGHT_BOX_BUTTON_F),
	LIGHT_BOX_BUTTON_G(ComponentID.LIGHT_BOX_BUTTON_G),
	LIGHT_BOX_BUTTON_H(ComponentID.LIGHT_BOX_BUTTON_H),

	LIGHT_BOX_WINDOW(ComponentID.LIGHT_BOX_LIGHT_BOX_WINDOW),

	NIGHTMARE_ZONE(WidgetID.NIGHTMARE_ZONE_GROUP_ID, 0),

	NIGHTMARE_PILLAR_HEALTH(WidgetID.NIGHTMARE_PILLAR_HEALTH_GROUP_ID, 1),

	RAIDS_POINTS_INFOBOX(ComponentID.RAIDS_POINTS_INFOBOX),

	RAIDS_PRIVATE_STORAGE_ITEM_CONTAINER(ComponentID.CHAMBERS_OF_XERIC_STORAGE_UNIT_PRIVATE_ITEM_CONTAINER),

	TOB_PARTY_INTERFACE(ComponentID.TOB_PARTY_INTERFACE),
	TOB_PARTY_STATS(ComponentID.TOB_PARTY_STATS),
	TOB_HEALTH_BAR(ComponentID.TOB_HEALTHBAR_CONTAINER),

	BLAST_FURNACE_COFFER(WidgetID.BLAST_FURNACE_GROUP_ID, 2),

	PYRAMID_PLUNDER_DATA(WidgetID.PYRAMID_PLUNDER_GROUP_ID, 2),

	EXPERIENCE_TRACKER(WidgetID.EXPERIENCE_TRACKER_GROUP_ID, 0),
	EXPERIENCE_TRACKER_WIDGET(ComponentID.EXPERIENCE_TRACKER_WIDGET),
	EXPERIENCE_TRACKER_BOTTOM_BAR(ComponentID.EXPERIENCE_TRACKER_BOTTOM_BAR),

	FISHING_TRAWLER_CONTRIBUTION(WidgetID.FISHING_TRAWLER_GROUP_ID, 13),
	FISHING_TRAWLER_TIMER(WidgetID.FISHING_TRAWLER_GROUP_ID, 14),

	TITHE_FARM(WidgetID.TITHE_FARM_GROUP_ID, 2),

	BARROWS_BROTHERS(ComponentID.BARROWS_BROTHERS),
	BARROWS_POTENTIAL(ComponentID.BARROWS_POTENTIAL),
	BARROWS_PUZZLE_PARENT(ComponentID.BARROWS_PUZZLE_PARENT),
	BARROWS_PUZZLE_ANSWER1(ComponentID.BARROWS_PUZZLE_ANSWER1),
	BARROWS_PUZZLE_ANSWER1_CONTAINER(ComponentID.BARROWS_PUZZLE_ANSWER1_CONTAINER),
	BARROWS_PUZZLE_ANSWER2(ComponentID.BARROWS_PUZZLE_ANSWER2),
	BARROWS_PUZZLE_ANSWER2_CONTAINER(ComponentID.BARROWS_PUZZLE_ANSWER2_CONTAINER),
	BARROWS_PUZZLE_ANSWER3(ComponentID.BARROWS_PUZZLE_ANSWER3),
	BARROWS_PUZZLE_ANSWER3_CONTAINER(ComponentID.BARROWS_PUZZLE_ANSWER3_CONTAINER),
	BARROWS_FIRST_PUZZLE(ComponentID.BARROWS_PUZZLE_SEQUENCE_1),

	BLAST_MINE(WidgetID.BLAST_MINE_GROUP_ID, 2),

	FAIRY_RING(WidgetID.FAIRY_RING_GROUP_ID, 0),

	FAIRY_RING_HEADER(ComponentID.FAIRY_RING_PANEL_HEADER),
	FAIRY_RING_LIST(ComponentID.FAIRY_RING_PANEL_LIST),
	FAIRY_RING_FAVORITES(ComponentID.FAIRY_RING_PANEL_FAVORITES),
	FAIRY_RING_LIST_SEPARATOR(ComponentID.FAIRY_RING_PANEL_SEPARATOR),
	FAIRY_RING_LIST_SCROLLBAR(ComponentID.FAIRY_RING_PANEL_SCROLLBAR),

	DESTROY_ITEM(WidgetID.DESTROY_ITEM_GROUP_ID, 0),
	DESTROY_ITEM_NAME(ComponentID.DESTROY_ITEM_NAME),
	DESTROY_ITEM_YES(ComponentID.DESTROY_ITEM_YES),
	DESTROY_ITEM_NO(ComponentID.DESTROY_ITEM_NO),

	VARROCK_MUSEUM_QUESTION(ComponentID.VARROCK_MUSEUM_QUESTION),
	VARROCK_MUSEUM_FIRST_ANSWER(ComponentID.VARROCK_MUSEUM_FIRST_ANSWER),
	VARROCK_MUSEUM_SECOND_ANSWER(ComponentID.VARROCK_MUSEUM_SECOND_ANSWER),
	VARROCK_MUSEUM_THIRD_ANSWER(ComponentID.VARROCK_MUSEUM_THIRD_ANSWER),

	KILL_LOG_TITLE(ComponentID.KILL_LOG_TITLE),
	KILL_LOG_MONSTER(ComponentID.KILL_LOG_MONSTER),
	KILL_LOG_KILLS(ComponentID.KILL_LOG_KILLS),
	KILL_LOG_STREAK(ComponentID.KILL_LOG_STREAK),

	ADVENTURE_LOG(ComponentID.ADVENTURE_LOG_CONTAINER),

	COLLECTION_LOG(ComponentID.COLLECTION_LOG_CONTAINER),

	COLLECTION_LOG_TABS(ComponentID.COLLECTION_LOG_TABS),
	COLLECTION_LOG_ENTRY(ComponentID.COLLECTION_LOG_ENTRY),
	COLLECTION_LOG_ENTRY_HEADER(ComponentID.COLLECTION_LOG_ENTRY_HEADER),
	COLLECTION_LOG_ENTRY_ITEMS(ComponentID.COLLECTION_LOG_ENTRY_ITEMS),

	GENERIC_SCROLL_TEXT(ComponentID.GENERIC_SCROLL_TEXT),

	WORLD_SWITCHER_LIST(ComponentID.WORLD_SWITCHER_WORLD_LIST),

	FOSSIL_ISLAND_OXYGENBAR(WidgetID.FOSSIL_ISLAND_OXYGENBAR_ID, 1),

	SPELL_LUMBRIDGE_HOME_TELEPORT(ComponentID.SPELLBOOK_LUMBRIDGE_HOME_TELEPORT),
	SPELL_EDGEVILLE_HOME_TELEPORT(ComponentID.SPELLBOOK_EDGEVILLE_HOME_TELEPORT),
	SPELL_LUNAR_HOME_TELEPORT(ComponentID.SPELLBOOK_LUNAR_HOME_TELEPORT),
	SPELL_ARCEUUS_HOME_TELEPORT(ComponentID.SPELLBOOK_ARCEUUS_HOME_TELEPORT),
	SPELL_KOUREND_HOME_TELEPORT(ComponentID.SPELLBOOK_KOUREND_HOME_TELEPORT),
	SPELL_CATHERBY_HOME_TELEPORT(ComponentID.SPELLBOOK_CATHERBY_HOME_TELEPORT),
	SPELL_LUNAR_FERTILE_SOIL(ComponentID.SPELLBOOK_FERTILE_SOIL),

	PVP_WILDERNESS_SKULL_CONTAINER(ComponentID.PVP_WILDERNESS_SKULL_CONTAINER),
	PVP_SKULL_CONTAINER(ComponentID.PVP_SKULL_CONTAINER),
	PVP_WORLD_SAFE_ZONE(ComponentID.PVP_SAFE_ZONE),

	PVP_WILDERNESS_LEVEL(ComponentID.PVP_WILDERNESS_LEVEL),
	PVP_KILLDEATH_COUNTER(ComponentID.PVP_KILLDEATH_RATIO),

	ZEAH_MESS_HALL_COOKING_DISPLAY(ComponentID.ZEAH_MESS_HALL_COOKING_DISPLAY),

	LOOTING_BAG_CONTAINER(ComponentID.LOOTING_BAG_LOOTING_BAG_INVENTORY),

	SKOTIZO_CONTAINER(ComponentID.SKOTIZO_CONTAINER),

	CHARACTER_SUMMARY_CONTAINER(ComponentID.CHARACTER_SUMMARY_CONTAINER),

	QUESTLIST_BOX(ComponentID.QUEST_LIST_BOX),
	QUESTLIST_CONTAINER(ComponentID.QUEST_LIST_CONTAINER),

	SEED_VAULT_TITLE_CONTAINER(ComponentID.SEED_VAULT_TITLE_CONTAINER),
	SEED_VAULT_ITEM_CONTAINER(ComponentID.SEED_VAULT_ITEM_CONTAINER),
	SEED_VAULT_ITEM_TEXT(ComponentID.SEED_VAULT_ITEM_TEXT),
	SEED_VAULT_SEARCH_BUTTON(ComponentID.SEED_VAULT_SEARCH_BUTTON),
	SEED_VAULT_INVENTORY_ITEMS_CONTAINER(ComponentID.SEED_VAULT_INVENTORY_ITEM_CONTAINER),

	SETTINGS_SIDE_CAMERA_ZOOM_SLIDER_TRACK(ComponentID.SETTINGS_SIDE_CAMERA_ZOOM_SLIDER_TRACK),
	SETTINGS_SIDE_MUSIC_SLIDER(ComponentID.SETTINGS_SIDE_MUSIC_SLIDER),
	SETTINGS_SIDE_MUSIC_SLIDER_STEP_HOLDER(ComponentID.SETTINGS_SIDE_MUSIC_SLIDER_STEP_HOLDER),
	SETTINGS_SIDE_SOUND_EFFECT_SLIDER(ComponentID.SETTINGS_SIDE_SOUND_EFFECT_SLIDER),
	SETTINGS_SIDE_AREA_SOUND_SLIDER(ComponentID.SETTINGS_SIDE_AREA_SOUND_SLIDER),

	SETTINGS_INIT(ComponentID.SETTINGS_INIT),

	ACHIEVEMENT_DIARY_CONTAINER(ComponentID.ACHIEVEMENT_DIARY_CONTAINER),

	SKILLS_CONTAINER(ComponentID.SKILLS_CONTAINER),

	GAUNTLET_TIMER_CONTAINER(ComponentID.GAUNTLET_TIMER_CONTAINER),
	HALLOWED_SEPULCHRE_TIMER_CONTAINER(ComponentID.HALLOWED_SEPULCHRE_TIMER_CONTAINER),

	HEALTH_OVERLAY_BAR(ComponentID.HEALTH_HEALTHBAR_CONTAINER),
	HEALTH_OVERLAY_BAR_TEXT(ComponentID.HEALTH_HEALTHBAR_TEXT),

	TRAILBLAZER_AREA_TELEPORT(ComponentID.TRAILBLAZER_AREAS_TELEPORT),

	MULTICOMBAT_FIXED(ComponentID.FIXED_VIEWPORT_MULTICOMBAT_INDICATOR),
	MULTICOMBAT_RESIZABLE_MODERN(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_MULTICOMBAT_INDICATOR),
	MULTICOMBAT_RESIZABLE_CLASSIC(ComponentID.RESIZABLE_VIEWPORT_MULTICOMBAT_INDICATOR),

	TEMPOROSS_STATUS_INDICATOR(ComponentID.TEMPOROSS_STATUS_INDICATOR),
	TEMPOROSS_LOBBY(ComponentID.TEMPOROSS_LOBBY_LOBBY),

	CLAN_LAYER(ComponentID.CLAN_LAYER),
	CLAN_HEADER(ComponentID.CLAN_HEADER),
	CLAN_MEMBER_LIST(ComponentID.CLAN_MEMBERS),

	CLAN_GUEST_LAYER(ComponentID.CLAN_GUEST_LAYER),
	CLAN_GUEST_HEADER(ComponentID.CLAN_GUEST_HEADER),
	CLAN_GUEST_MEMBER_LIST(ComponentID.CLAN_GUEST_MEMBERS),

	POH_TREASURE_CHEST_INVENTORY_CONTAINER(WidgetID.POH_TREASURE_CHEST_INVENTORY_GROUP_ID, 0),

	TRADE_WINDOW_HEADER(ComponentID.TRADE_HEADER),

	TOA_PARTY_LAYER(WidgetID.TOA_PARTY_GROUP_ID, 2),
	TOA_RAID_LAYER(WidgetID.TOA_RAID_GROUP_ID, 3),

	QUICK_PRAYER_PRAYERS(WidgetID.QUICK_PRAYERS_GROUP_ID, 4),

	GOTR_MAIN_DISPLAY(WidgetID.GOTR_GROUP_ID, 2),
	TROUBLE_BREWING_SCORE(ComponentID.TROUBLE_BREWING_SCORE),
	TROUBLE_BREWING_LOBBY(WidgetID.TROUBLE_BREWING_LOBBY_GROUP_ID, 2),
	MORTTON_TEMPLE_STATUS(WidgetID.MORTTON_TEMPLE_GROUP_ID, 2),
	BGR_RANK_DISPLAY_DRAUGHTS(WidgetID.BGR_RANK_DRAUGHTS_GROUP_ID, 2),
	BGR_RANK_DISPLAY_RUNELINK(WidgetID.BGR_RANK_RUNELINK_GROUP_ID, 2),
	BGR_RANK_DISPLAY_RUNESQUARES(WidgetID.BGR_RANK_RUNESQUARES_GROUP_ID, 2),
	BGR_RANK_DISPLAY_RUNEVERSI(WidgetID.BGR_RANK_RUNEVERSI_GROUP_ID, 2),
	AGILITY_ARENA_LIGHT_INDICATOR(WidgetID.AGILITY_ARENA_HUD_GROUP_ID, 2),
	GNOMEBALL_SCORE(WidgetID.GNOMEBALL_SCORE_GROUP_ID, 2),
	MTA_ALCHEMY_POINTS(WidgetID.MTA_ALCHEMY_GROUP_ID, 2),
	MTA_ENCHANT_POINTS(WidgetID.MTA_ENCHANT_GROUP_ID, 2),
	MTA_ENCHANT_BONUS(WidgetID.MTA_ENCHANT_GROUP_ID, 8),
	MTA_GRAVEYARD_POINTS(WidgetID.MTA_GRAVEYARD_GROUP_ID, 2),
	MTA_GRAVEYARD_VALUES(WidgetID.MTA_GRAVEYARD_GROUP_ID, 8),
	MTA_TELEKINETIC_POINTS(WidgetID.MTA_TELEKINETIC_GROUP_ID, 2),
	MTA_TELEKINETIC_SOLVED(WidgetID.MTA_TELEKINETIC_GROUP_ID, 8),

	STRANGLER_INFECTION_OVERLAY(WidgetID.THE_STRANGLER_INFECTION_GROUP_ID, 4),
	SANITY_OVERLAY(WidgetID.SANITY_GROUP_ID, 3),

	/**
	 * OpenOSRS
	 */

	FAIRY_RING_LEFT_ORB_CLOCKWISE(WidgetID.FAIRY_RING_GROUP_ID, WidgetID.FairyRing.LEFT_ORB_CLOCKWISE),
	FAIRY_RING_LEFT_ORB_COUNTER_CLOCKWISE(WidgetID.FAIRY_RING_GROUP_ID, WidgetID.FairyRing.LEFT_ORB_COUNTER_CLOCKWISE),
	FAIRY_RING_MIDDLE_ORB_CLOCKWISE(WidgetID.FAIRY_RING_GROUP_ID, WidgetID.FairyRing.MIDDLE_ORB_CLOCKWISE),
	FAIRY_RING_MIDDLE_ORB_COUNTER_CLOCKWISE(WidgetID.FAIRY_RING_GROUP_ID, WidgetID.FairyRing.MIDDLE_ORB_COUNTER_CLOCKWISE),
	FAIRY_RING_RIGHT_ORB_CLOCKWISE(WidgetID.FAIRY_RING_GROUP_ID, WidgetID.FairyRing.RIGHT_ORB_CLOCKWISE),
	FAIRY_RING_RIGHT_ORB_COUNTER_CLOCKWISE(WidgetID.FAIRY_RING_GROUP_ID, WidgetID.FairyRing.RIGHT_ORB_COUNTER_CLOCKWISE),

	MINIMAP_SPEC_CLICKBOX(WidgetID.MINIMAP_GROUP_ID, WidgetID.Minimap.SPEC_CLICKBOX),

	LOGIN_CLICK_TO_PLAY_SCREEN_OPEN_STORE_BUTTON(WidgetID.LOGIN_CLICK_TO_PLAY_GROUP_ID, WidgetID.LoginClickToPlayScreen.OPEN_STORE_BUTTON),
	LOGIN_CLICK_TO_PLAY_SCREEN_VIEW_INBOX_BUTTON(WidgetID.LOGIN_CLICK_TO_PLAY_GROUP_ID, WidgetID.LoginClickToPlayScreen.VIEW_INBOX_BUTTON),
	LOGIN_CLICK_TO_PLAY_SCREEN_CLICK_HERE_TO_PLAY_BUTTON(WidgetID.LOGIN_CLICK_TO_PLAY_GROUP_ID, WidgetID.LoginClickToPlayScreen.CLICK_HERE_TO_PLAY_BUTTON),

	RESIZABLE_VIEWPORT_BOTTOM_LINE_COMBAT_TAB(WidgetID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetID.ResizableViewportBottomLine.COMBAT_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_STATS_TAB(WidgetID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetID.ResizableViewportBottomLine.STATS_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_QUESTS_TAB(WidgetID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetID.ResizableViewportBottomLine.QUESTS_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_EQUIP_TAB(WidgetID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetID.ResizableViewportBottomLine.EQUIP_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_MAGIC_TAB(WidgetID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetID.ResizableViewportBottomLine.MAGIC_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_FRIEND_CHAT_TAB(WidgetID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetID.ResizableViewportBottomLine.FRIENDS_CHAT_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_FRIEND_TAB(WidgetID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetID.ResizableViewportBottomLine.FRIENDS_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_IGNORES_TAB(WidgetID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetID.ResizableViewportBottomLine.IGNORES_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_IGNORES_ICON(WidgetID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetID.ResizableViewportBottomLine.IGNORES_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_SETTINGS_TAB(WidgetID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetID.ResizableViewportBottomLine.SETTINGS_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_MUSIC_TAB(WidgetID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetID.ResizableViewportBottomLine.MUSIC_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_EMOTES_TAB(WidgetID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetID.ResizableViewportBottomLine.EMOTES_TAB),

	PRAYER_THICK_SKIN(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.THICK_SKIN),
	PRAYER_BURST_OF_STRENGTH(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.BURST_OF_STRENGTH),
	PRAYER_CLARITY_OF_THOUGHT(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.CLARITY_OF_THOUGHT),
	PRAYER_SHARP_EYE(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.SHARP_EYE),
	PRAYER_MYSTIC_WILL(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.MYSTIC_WILL),
	PRAYER_ROCK_SKIN(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.ROCK_SKIN),
	PRAYER_SUPERHUMAN_STRENGTH(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.SUPERHUMAN_STRENGTH),
	PRAYER_IMPROVED_REFLEXES(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.IMPROVED_REFLEXES),
	PRAYER_RAPID_RESTORE(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RAPID_RESTORE),
	PRAYER_RAPID_HEAL(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RAPID_HEAL),
	PRAYER_PROTECT_ITEM(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.PROTECT_ITEM),
	PRAYER_HAWK_EYE(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.HAWK_EYE),
	PRAYER_MYSTIC_LORE(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.MYSTIC_LORE),
	PRAYER_STEEL_SKIN(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.STEEL_SKIN),
	PRAYER_ULTIMATE_STRENGTH(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.ULTIMATE_STRENGTH),
	PRAYER_INCREDIBLE_REFLEXES(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.INCREDIBLE_REFLEXES),
	PRAYER_PROTECT_FROM_MAGIC(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.PROTECT_FROM_MAGIC),
	PRAYER_PROTECT_FROM_MISSILES(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.PROTECT_FROM_MISSILES),
	PRAYER_PROTECT_FROM_MELEE(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.PROTECT_FROM_MELEE),
	PRAYER_EAGLE_EYE(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.EAGLE_EYE),
	PRAYER_MYSTIC_MIGHT(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.MYSTIC_MIGHT),
	PRAYER_RETRIBUTION(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RETRIBUTION),
	PRAYER_REDEMPTION(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.REDEMPTION),
	PRAYER_SMITE(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.SMITE),
	PRAYER_PRESERVE(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.PRESERVE),
	PRAYER_CHIVALRY(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.CHIVALRY),
	PRAYER_PIETY(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.PIETY),
	PRAYER_RIGOUR(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RIGOUR),
	PRAYER_AUGURY(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.AUGURY),

	WORLD_MAP_BUTTON_BORDER(WidgetID.MINIMAP_GROUP_ID, WidgetID.Minimap.WORLDMAP_ORB),

	EQUIPMENT_STATS(WidgetID.EQUIPMENT_GROUP_ID, WidgetID.Equipment.STATS),
	EQUIPMENT_PRICES(WidgetID.EQUIPMENT_GROUP_ID, WidgetID.Equipment.PRICES),
	EQUIPMENT_DEATH(WidgetID.EQUIPMENT_GROUP_ID, WidgetID.Equipment.DEATH),
	EQUIPMENT_FOLLOWER(WidgetID.EQUIPMENT_GROUP_ID, WidgetID.Equipment.FOLLOWER),
	EQUIPMENT_HELMET(WidgetID.EQUIPMENT_GROUP_ID, WidgetID.Equipment.HELMET),
	EQUIPMENT_CAPE(WidgetID.EQUIPMENT_GROUP_ID, WidgetID.Equipment.CAPE),
	EQUIPMENT_AMULET(WidgetID.EQUIPMENT_GROUP_ID, WidgetID.Equipment.AMULET),
	EQUIPMENT_WEAPON(WidgetID.EQUIPMENT_GROUP_ID, WidgetID.Equipment.WEAPON),
	EQUIPMENT_BODY(WidgetID.EQUIPMENT_GROUP_ID, WidgetID.Equipment.BODY),
	EQUIPMENT_SHIELD(WidgetID.EQUIPMENT_GROUP_ID, WidgetID.Equipment.SHIELD),
	EQUIPMENT_LEGS(WidgetID.EQUIPMENT_GROUP_ID, WidgetID.Equipment.LEGS),
	EQUIPMENT_GLOVES(WidgetID.EQUIPMENT_GROUP_ID, WidgetID.Equipment.GLOVES),
	EQUIPMENT_BOOTS(WidgetID.EQUIPMENT_GROUP_ID, WidgetID.Equipment.BOOTS),
	EQUIPMENT_RING(WidgetID.EQUIPMENT_GROUP_ID, WidgetID.Equipment.RING),
	EQUIPMENT_AMMO(WidgetID.EQUIPMENT_GROUP_ID, WidgetID.Equipment.AMMO),

	MINIGAME_DIALOG(WidgetID.DIALOG_MINIGAME_GROUP_ID, 0),
	MINIGAME_DIALOG_TEXT(WidgetID.DIALOG_MINIGAME_GROUP_ID, WidgetID.MinigameDialog.TEXT),
	MINIGAME_DIALOG_CONTINUE(WidgetID.DIALOG_MINIGAME_GROUP_ID, WidgetID.MinigameDialog.CONTINUE),
	PEST_CONTROL_EXCHANGE_WINDOW(WidgetID.PEST_CONTROL_EXCHANGE_WINDOW_GROUP_ID, 0),
	PEST_CONTROL_EXCHANGE_WINDOW_POINTS(WidgetID.PEST_CONTROL_EXCHANGE_WINDOW_GROUP_ID, WidgetID.PestControlExchangeWindow.POINTS),

	GRAND_EXCHANGE_HISTORY_BUTTON(WidgetID.GRAND_EXCHANGE_GROUP_ID, WidgetID.GrandExchange.HISTORY_BUTTON),
	GRAND_EXCHANGE_BACK_BUTTON(WidgetID.GRAND_EXCHANGE_GROUP_ID, WidgetID.GrandExchange.BACK_BUTTON),
	GRAND_EXCHANGE_OFFER1(WidgetID.GRAND_EXCHANGE_GROUP_ID, WidgetID.GrandExchange.OFFER1),
	GRAND_EXCHANGE_OFFER2(WidgetID.GRAND_EXCHANGE_GROUP_ID, WidgetID.GrandExchange.OFFER2),
	GRAND_EXCHANGE_OFFER3(WidgetID.GRAND_EXCHANGE_GROUP_ID, WidgetID.GrandExchange.OFFER3),
	GRAND_EXCHANGE_OFFER4(WidgetID.GRAND_EXCHANGE_GROUP_ID, WidgetID.GrandExchange.OFFER4),
	GRAND_EXCHANGE_OFFER5(WidgetID.GRAND_EXCHANGE_GROUP_ID, WidgetID.GrandExchange.OFFER5),
	GRAND_EXCHANGE_OFFER6(WidgetID.GRAND_EXCHANGE_GROUP_ID, WidgetID.GrandExchange.OFFER6),
	GRAND_EXCHANGE_OFFER7(WidgetID.GRAND_EXCHANGE_GROUP_ID, WidgetID.GrandExchange.OFFER7),
	GRAND_EXCHANGE_OFFER8(WidgetID.GRAND_EXCHANGE_GROUP_ID, WidgetID.GrandExchange.OFFER8),

	GRAND_EXCHANGE_OFFER_CONFIRM_BUTTON(WidgetID.GRAND_EXCHANGE_GROUP_ID, WidgetID.GrandExchange.OFFER_CONFIRM_BUTTON),

	SMITHING_ANVIL_DAGGER(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.DAGGER),
	SMITHING_ANVIL_SWORD(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.SWORD),
	SMITHING_ANVIL_SCIMITAR(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.SCIMITAR),
	SMITHING_ANVIL_LONG_SWORD(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.LONG_SWORD),
	SMITHING_ANVIL_TWO_H_SWORD(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.TWO_H_SWORD),
	SMITHING_ANVIL_AXE(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.AXE),
	SMITHING_ANVIL_MACE(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.MACE),
	SMITHING_ANVIL_WARHAMMER(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.WARHAMMER),
	SMITHING_ANVIL_BATTLE_AXE(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.BATTLE_AXE),
	SMITHING_ANVIL_CLAWS(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.CLAWS),
	SMITHING_ANVIL_CHAIN_BODY(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.CHAIN_BODY),
	SMITHING_ANVIL_PLATE_LEGS(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.PLATE_LEGS),
	SMITHING_ANVIL_PLATE_SKIRT(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.PLATE_SKIRT),
	SMITHING_ANVIL_PLATE_BODY(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.PLATE_BODY),
	SMITHING_ANVIL_NAILS(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.NAILS),
	SMITHING_ANVIL_MED_HELM(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.MED_HELM),
	SMITHING_ANVIL_FULL_HELM(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.FULL_HELM),
	SMITHING_ANVIL_SQ_SHIELD(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.SQ_SHIELD),
	SMITHING_ANVIL_KITE_SHIELD(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.KITE_SHIELD),
	SMITHING_ANVIL_DART_TIPS(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.DART_TIPS),
	SMITHING_ANVIL_ARROW_HEADS(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.ARROW_HEADS),
	SMITHING_ANVIL_KNIVES(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.KNIVES),
	SMITHING_ANVIL_JAVELIN_HEADS(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.JAVELIN_HEADS),
	SMITHING_ANVIL_BOLTS(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.BOLTS),
	SMITHING_ANVIL_LIMBS(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.LIMBS),
	SMITHING_ANVIL_EXCLUSIVE1(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.EXCLUSIVE1),
	SMITHING_ANVIL_EXCLUSIVE2(WidgetID.SMITHING_GROUP_ID, WidgetID.Smithing.EXCLUSIVE2),

	MINIMAP_WORLD_ORB(WidgetID.MINIMAP_GROUP_ID, WidgetID.Minimap.WORLDMAP_ORB),

	COMBAT_WEAPON(WidgetID.COMBAT_GROUP_ID, WidgetID.Combat.WEAPON_NAME),

	COMBAT_SPECIAL_ATTACK(WidgetID.COMBAT_GROUP_ID, WidgetID.Combat.SPECIAL_ATTACK_BAR),
	COMBAT_SPECIAL_ATTACK_CLICKBOX(WidgetID.COMBAT_GROUP_ID, WidgetID.Combat.SPECIAL_ATTACK_CLICKBOX),
	COMBAT_TOOLTIP(WidgetID.COMBAT_GROUP_ID, WidgetID.Combat.TOOLTIP),

	MULTI_SKILL_MENU(WidgetID.MULTISKILL_MENU_GROUP_ID, 0),

	DIALOG2_SPRITE(WidgetID.DIALOG_SPRITE2_ID, 0),
	DIALOG2_SPRITE_SPRITE1(WidgetID.DIALOG_SPRITE2_ID, WidgetID.DialogSprite2.SPRITE1),
	DIALOG2_SPRITE_SPRITE2(WidgetID.DIALOG_SPRITE2_ID, WidgetID.DialogSprite2.SPRITE2),
	DIALOG2_SPRITE_TEXT(WidgetID.DIALOG_SPRITE2_ID, WidgetID.DialogSprite2.TEXT),
	DIALOG2_SPRITE_CONTINUE(WidgetID.DIALOG_SPRITE2_ID, WidgetID.DialogSprite2.CONTINUE),

	DIALOG_OPTION_OPTION1(WidgetID.DIALOG_OPTION_GROUP_ID, WidgetID.DialogOption.OPTIONS),

	DIALOG_NOTIFICATION_TEXT(WidgetID.DIALOG_NOTIFICATION_GROUP_ID, WidgetID.DialogNotification.TEXT),
	DIALOG_NOTIFICATION_CONTINUE(WidgetID.DIALOG_NOTIFICATION_GROUP_ID, WidgetID.DialogNotification.CONTINUE),

	LEVEL_UP_CONTINUE(WidgetID.LEVEL_UP_GROUP_ID, WidgetID.LevelUp.CONTINUE),

	THEATRE_OF_BLOOD_PARTY(WidgetID.THEATRE_OF_BLOOD_PARTY_GROUP_ID, WidgetID.TheatreOfBloodParty.CONTAINER),

	LIGHT_BOX_BUTTON_CONTAINER(WidgetID.LIGHT_BOX_GROUP_ID, WidgetID.LightBox.LIGHT_BOX_BUTTON_CONTAINER),

	THEATRE_OF_BLOOD_HEALTH_ORBS(WidgetID.THEATRE_OF_BLOOD_GROUP_ID, WidgetID.TheatreOfBlood.ORB_BOX),
	THEATRE_OF_BLOOD_BOSS_HEALTH(WidgetID.THEATRE_OF_BLOOD_GROUP_ID, WidgetID.TheatreOfBlood.BOSS_HEALTH_BAR),
	THEATRE_OF_BLOOD_RAIDING_PARTY(WidgetID.THEATRE_OF_BLOOD_GROUP_ID, WidgetID.TheatreOfBlood.RAIDING_PARTY),

	WORLD_SWITCHER_CONTAINER(WidgetID.WORLD_SWITCHER_GROUP_ID, WidgetID.WorldSwitcher.CONTAINER),

	WORLD_SWITCHER_LOGOUT_BUTTON(WidgetID.WORLD_SWITCHER_GROUP_ID, WidgetID.WorldSwitcher.LOGOUT_BUTTON),

	FOSSIL_MUSHROOM_TELEPORT(WidgetID.FOSSIL_ISLAND_MUSHROOM_TELE_GROUP_ID, WidgetID.FossilMushroomTeleport.ROOT),
	FOSSIL_MUSHROOM_HOUSE(WidgetID.FOSSIL_ISLAND_MUSHROOM_TELE_GROUP_ID, WidgetID.FossilMushroomTeleport.HOUSE_ON_HILL),
	FOSSIL_MUSHROOM_VALLEY(WidgetID.FOSSIL_ISLAND_MUSHROOM_TELE_GROUP_ID, WidgetID.FossilMushroomTeleport.VERDANT_VALLEY),
	FOSSIL_MUSHROOM_SWAMP(WidgetID.FOSSIL_ISLAND_MUSHROOM_TELE_GROUP_ID, WidgetID.FossilMushroomTeleport.SWAMP),
	FOSSIL_MUSHROOM_MEADOW(WidgetID.FOSSIL_ISLAND_MUSHROOM_TELE_GROUP_ID, WidgetID.FossilMushroomTeleport.MUSHROOM_MEADOW),

	SPELLBOOK(WidgetID.SPELLBOOK_GROUP_ID, 0),
	SPELLBOOK_FILTERED_BOUNDS(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.FILTERED_SPELLS_BOUNDS),

	/* STANDARD SPELL BOOK WIDGETS*/
	SPELL_WIND_STRIKE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.WIND_STRIKE),
	SPELL_CONFUSE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.CONFUSE),
	SPELL_ENCHANT_CROSSBOW_BOLT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.ENCHANT_CROSSBOW_BOLT),
	SPELL_WATER_STRIKE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.WATER_STRIKE),

	SPELL_JEWELLERY_ENCHANTMENTS(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.JEWELLERY_ENCHANTMENTS),
	SPELL_LVL_1_ENCHANT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.LVL_1_ENCHANT),
	SPELL_LVL_2_ENCHANT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.LVL_2_ENCHANT),
	SPELL_LVL_3_ENCHANT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.LVL_3_ENCHANT),
	SPELL_LVL_4_ENCHANT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.LVL_4_ENCHANT),
	SPELL_LVL_5_ENCHANT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.LVL_5_ENCHANT),
	SPELL_LVL_6_ENCHANT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.LVL_6_ENCHANT),
	SPELL_LVL_7_ENCHANT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.LVL_7_ENCHANT),

	SPELL_EARTH_STRIKE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.EARTH_STRIKE),
	SPELL_WEAKEN(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.WEAKEN),
	SPELL_FIRE_STRIKE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.FIRE_STRIKE),
	SPELL_BONES_TO_BANANAS(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.BONES_TO_BANANAS),
	SPELL_WIND_BOLT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.WIND_BOLT),
	SPELL_CURSE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.CURSE),
	SPELL_BIND(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.BIND),
	SPELL_LOW_LEVEL_ALCHEMY(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.LOW_LEVEL_ALCHEMY),
	SPELL_WATER_BOLT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.WATER_BOLT),
	SPELL_VARROCK_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.VARROCK_TELEPORT),
	SPELL_EARTH_BOLT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.EARTH_BOLT),
	SPELL_LUMBRIDGE_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.LUMBRIDGE_TELEPORT),
	SPELL_TELEKINETIC_GRAB(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.TELEKINETIC_GRAB),
	SPELL_FIRE_BOLT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.FIRE_BOLT),
	SPELL_FALADOR_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.FALADOR_TELEPORT),
	SPELL_CRUMBLE_UNDEAD(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.CRUMBLE_UNDEAD),
	SPELL_TELEPORT_TO_HOUSE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.TELEPORT_TO_HOUSE),
	SPELL_WIND_BLAST(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.WIND_BLAST),
	SPELL_SUPERHEAT_ITEM(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SUPERHEAT_ITEM),
	SPELL_CAMELOT_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.CAMELOT_TELEPORT),
	SPELL_WATER_BLAST(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.WATER_BLAST),
	KOUREND_CASTLE_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.KOUREND_CASTLE_TELEPORT),
	SPELL_IBAN_BLAST(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.IBAN_BLAST),
	SPELL_SNARE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SNARE),
	SPELL_MAGIC_DART(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.MAGIC_DART),
	SPELL_ARDOUGNE_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.ARDOUGNE_TELEPORT),
	SPELL_EARTH_BLAST(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.EARTH_BLAST),
	SPELL_CIVITAS_ILLA_FORTIS_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.CIVITAS_ILLA_FORTIS_TELEPORT),
	SPELL_HIGH_LEVEL_ALCHEMY(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.HIGH_LEVEL_ALCHEMY),
	SPELL_CHARGE_WATER_ORB(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.CHARGE_WATER_ORB),
	SPELL_WATCHTOWER_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.WATCHTOWER_TELEPORT),
	SPELL_FIRE_BLAST(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.FIRE_BLAST),
	SPELL_CHARGE_EARTH_ORB(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.CHARGE_EARTH_ORB),
	SPELL_BONES_TO_PEACHES(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.BONES_TO_PEACHES),
	SPELL_SARADOMIN_STRIKE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SARADOMIN_STRIKE),
	SPELL_CLAWS_OF_GUTHIX(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.CLAWS_OF_GUTHIX),
	SPELL_FLAMES_OF_ZAMORAK(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.FLAMES_OF_ZAMORAK),
	SPELL_TROLLHEIM_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.TROLLHEIM_TELEPORT),
	SPELL_WIND_WAVE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.WIND_WAVE),
	SPELL_CHARGE_FIRE_ORB(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.CHARGE_FIRE_ORB),
	SPELL_TELEPORT_TO_APE_ATOLL(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.TELEPORT_TO_APE_ATOLL),
	SPELL_WATER_WAVE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.WATER_WAVE),
	SPELL_CHARGE_AIR_ORB(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.CHARGE_AIR_ORB),
	SPELL_VULNERABILITY(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.VULNERABILITY),
	SPELL_EARTH_WAVE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.EARTH_WAVE),
	SPELL_ENFEEBLE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.ENFEEBLE),
	SPELL_FIRE_WAVE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.FIRE_WAVE),
	SPELL_ENTANGLE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.ENTANGLE),
	SPELL_TELEOTHER_LUMBRIDGE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.TELEOTHER_LUMBRIDGE),
	SPELL_STUN(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.STUN),
	SPELL_CHARGE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.CHARGE),
	SPELL_WIND_SURGE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.WIND_SURGE),
	SPELL_TELEOTHER_FALADOR(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.TELEOTHER_FALADOR),
	SPELL_WATER_SURGE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.WATER_SURGE),
	SPELL_TELE_BLOCK(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.TELE_BLOCK),
	SPELL_TELEOTHER_CAMELOT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.TELEOTHER_CAMELOT),
	SPELL_EARTH_SURGE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.EARTH_SURGE),
	SPELL_FIRE_SURGE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.FIRE_SURGE),
	SPELL_BOUNTY_TARGET_TELEPORT2(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.BOUNTY_TARGET_TELEPORT),
	/* END OF STANDARD SPELL BOOK WIDGETS*/

	/* ANCIENT SPELL BOOK WIDGETS*/
	SPELL_ICE_RUSH(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.ICE_RUSH),
	SPELL_ICE_BLITZ(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.ICE_BLITZ),
	SPELL_ICE_BURST(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.ICE_BURST),
	SPELL_ICE_BARRAGE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.ICE_BARRAGE),
	SPELL_BLOOD_RUSH(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.BLOOD_RUSH),
	SPELL_BLOOD_BLITZ(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.BLOOD_BLITZ),
	SPELL_BLOOD_BURST(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.BLOOD_BURST),
	SPELL_BLOOD_BARRAGE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.BLOOD_BARRAGE),
	SPELL_SMOKE_RUSH(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SMOKE_RUSH),
	SPELL_SMOKE_BLITZ(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SMOKE_BLITZ),
	SPELL_SMOKE_BURST(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SMOKE_BURST),
	SPELL_SMOKE_BARRAGE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SMOKE_BARRAGE),
	SPELL_SHADOW_RUSH(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SHADOW_RUSH),
	SPELL_SHADOW_BLITZ(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SHADOW_BLITZ),
	SPELL_SHADOW_BURST(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SHADOW_BURST),
	SPELL_SHADOW_BARRAGE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SHADOW_BARRAGE),
	SPELL_PADDEWWA_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.PADDEWWA_TELEPORT),
	SPELL_SENNTISTEN_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SENNTISTEN_TELEPORT),
	SPELL_KHARYRLL_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.KHARYRLL_TELEPORT),
	SPELL_LASSAR_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.LASSAR_TELEPORT),
	SPELL_DAREEYAK_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.DAREEYAK_TELEPORT),
	SPELL_CARRALLANGER_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.CARRALLANGER_TELEPORT),
	SPELL_ANNAKARL_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.ANNAKARL_TELEPORT),
	SPELL_GHORROCK_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.GHORROCK_TELEPORT),
	SPELL_BOUNTY_TARGET_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.BOUNTY_TARGET_TELEPORT),
	/* END OF ANCIENT SPELL BOOK WIDGETS*/

	/* LUNAR SPELL BOOK WIDGETS*/
	SPELL_VENGEANCE_OTHER(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.VENGEANCE_OTHER),
	SPELL_VENGEANCE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.VENGEANCE),
	SPELL_BOUNTY_TARGET_TELEPORT3(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.BOUNTY_TARGET_TELEPORT),
	SPELL_BAKE_PIE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.BAKE_PIE),
	SPELL_CURE_PLANT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.CURE_PLANT),
	SPELL_MONSTER_EXAMINE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.MONSTER_EXAMINE),
	SPELL_NPC_CONTACT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.NPC_CONTACT),
	SPELL_CURE_OTHER(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.CURE_OTHER),
	SPELL_HUMIDIFY(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.HUMIDIFY),
	SPELL_MOONCLAN_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.MOONCLAN_TELEPORT),
	SPELL_TELE_GROUP_MOONCLAN(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.TELE_GROUP_MOONCLAN),
	SPELL_CURE_ME(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.CURE_ME),
	SPELL_HUNTER_KIT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.HUNTER_KIT),
	SPELL_WATERBIRTH_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.WATERBIRTH_TELEPORT),
	SPELL_TELE_GROUP_WATERBIRTH(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.TELE_GROUP_WATERBIRTH),
	SPELL_CURE_GROUP(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.CURE_GROUP),
	SPELL_STAT_SPY(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.STAT_SPY),
	SPELL_BARBARIAN_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.BARBARIAN_TELEPORT),
	SPELL_TELE_GROUP_BARBARIAN(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.TELE_GROUP_BARBARIAN),
	SPELL_SUPERGLASS_MAKE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SUPERGLASS_MAKE),
	SPELL_TAN_LEATHER(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.TAN_LEATHER),
	SPELL_KHAZARD_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.KHAZARD_TELEPORT),
	SPELL_TELE_GROUP_KHAZARD(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.TELE_GROUP_KHAZARD),
	SPELL_DREAM(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.DREAM),
	SPELL_STRING_JEWELLERY(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.STRING_JEWELLERY),
	SPELL_STAT_RESTORE_POT_SHARE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.STAT_RESTORE_POT_SHARE),
	SPELL_MAGIC_IMBUE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.MAGIC_IMBUE),
	SPELL_FERTILE_SOIL(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.FERTILE_SOIL),
	SPELL_BOOST_POTION_SHARE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.BOOST_POTION_SHARE),
	SPELL_FISHING_GUILD_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.FISHING_GUILD_TELEPORT),
	SPELL_TELE_GROUP_FISHING_GUILD(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.TELE_GROUP_FISHING_GUILD),
	SPELL_PLANK_MAKE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.PLANK_MAKE),
	SPELL_CATHERBY_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.CATHERBY_TELEPORT),
	SPELL_TELE_GROUP_CATHERBY(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.TELE_GROUP_CATHERBY),
	SPELL_RECHARGE_DRAGONSTONE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.RECHARGE_DRAGONSTONE),
	SPELL_ICE_PLATEAU_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.ICE_PLATEAU_TELEPORT),
	SPELL_TELE_GROUP_ICE_PLATEAU(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.TELE_GROUP_ICE_PLATEAU),
	SPELL_ENERGY_TRANSFER(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.ENERGY_TRANSFER),
	SPELL_HEAL_OTHER(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.HEAL_OTHER),
	SPELL_HEAL_GROUP(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.HEAL_GROUP),
	SPELL_SPELLBOOK_SWAP(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SPELLBOOK_SWAP),
	SPELL_GEOMANCY(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.GEOMANCY),
	SPELL_SPIN_FLAX(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SPIN_FLAX),
	SPELL_OURANIA_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.OURANIA_TELEPORT),
	/* END OF LUNAR SPELL BOOK WIDGETS*/
	SPELL_TOOLTIP(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.TOOLTIP),
	/* ARCEUUS SPELL BOOK WIDGETS*/
	SPELL_BASIC_REANIMATION(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.BASIC_REANIMATION),
	SPELL_ARCEUUS_LIBRARY_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.ARCEUUS_LIBRARY_TELEPORT),
	SPELL_ADEPT_REANIMATION(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.ADEPT_REANIMATION),
	SPELL_EXPERT_REANIMATION(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.EXPERT_REANIMATION),
	SPELL_MASTER_REANIMATION(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.MASTER_REANIMATION),
	SPELL_DRAYNOR_MANOR_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.DRAYNOR_MANOR_TELEPORT),
	SPELL_MIND_ALTAR_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.MIND_ALTAR_TELEPORT),
	SPELL_RESPAWN_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.RESPAWN_TELEPORT),
	SPELL_SALVE_GRAVEYARD_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SALVE_GRAVEYARD_TELEPORT),
	SPELL_FENKENSTRAINS_CASTLE_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.FENKENSTRAINS_CASTLE_TELEPORT),
	SPELL_WEST_ARDOUGNE_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.WEST_ARDOUGNE_TELEPORT),
	SPELL_HARMONY_ISLAND_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.HARMONY_ISLAND_TELEPORT),
	SPELL_CEMETERY_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.CEMETERY_TELEPORT),
	SPELL_RESURRECT_CROPS(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.RESURRECT_CROPS),
	SPELL_BARROWS_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.BARROWS_TELEPORT),
	SPELL_APE_ATOLL_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.APE_ATOLL_TELEPORT),
	SPELL_BATTLEFRONT_TELEPORT(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.BATTLEFRONT_TELEPORT),
	SPELL_INFERIOR_DEMONBANE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.INFERIOR_DEMONBANE),
	SPELL_SUPERIOR_DEMONBANE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SUPERIOR_DEMONBANE),
	SPELL_DARK_DEMONBANE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.DARK_DEMONBANE),
	SPELL_MARK_OF_DARKNESS(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.MARK_OF_DARKNESS),
	SPELL_GHOSTLY_GRASP(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.GHOSTLY_GRASP),
	SPELL_SKELETAL_GRASP(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SKELETAL_GRASP),
	SPELL_UNDEAD_GRASP(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.UNDEAD_GRASP),
	SPELL_WARD_OF_ARCEUUS(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.WARD_OF_ARCEUUS),
	SPELL_LESSER_CORRUPTION(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.LESSER_CORRUPTION),
	SPELL_GREATER_CORRUPTION(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.GREATER_CORRUPTION),
	SPELL_DEMONIC_OFFERING(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.DEMONIC_OFFERING),
	SPELL_SINISTER_OFFERING(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SINISTER_OFFERING),
	SPELL_DEGRIME(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.DEGRIME),
	SPELL_SHADOW_VEIL(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.SHADOW_VEIL),
	SPELL_VILE_VIGOUR(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.VILE_VIGOUR),
	SPELL_DARK_LURE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.DARK_LURE),
	SPELL_DEATH_CHARGE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.DEATH_CHARGE),
	SPELL_RESURRECT_LESSER_GHOST(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.RESURRECT_LESSER_GHOST),
	SPELL_RESURRECT_LESSER_SKELETON(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.RESURRECT_LESSER_SKELETON),
	SPELL_RESURRECT_LESSER_ZOMBIE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.RESURRECT_LESSER_ZOMBIE),
	SPELL_RESURRECT_SUPERIOR_GHOST(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.RESURRECT_SUPERIOR_GHOST),
	SPELL_RESURRECT_SUPERIOR_SKELETON(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.RESURRECT_SUPERIOR_SKELETON),
	SPELL_RESURRECT_SUPERIOR_ZOMBIE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.RESURRECT_SUPERIOR_ZOMBIE),
	SPELL_RESURRECT_GREATER_GHOST(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.RESURRECT_GREATER_GHOST),
	SPELL_RESURRECT_GREATER_SKELETON(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.RESURRECT_GREATER_SKELETON),
	SPELL_RESURRECT_GREATER_ZOMBIE(WidgetID.SPELLBOOK_GROUP_ID, WidgetID.SpellBook.RESURRECT_GREATER_ZOMBIE),
	/* END OF ARCEUUS SPELL BOOK WIDGETS*/

	MULTICOMBAT_RESIZEABLE(WidgetID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetID.ResizableViewport.MULTICOMBAT_INDICATOR),

	MUSICTAB_INTERFACE(WidgetID.MUSICTAB_GROUP_ID, 1),
	MUSICTAB_SONG_BOX(WidgetID.MUSICTAB_GROUP_ID, 2),
	MUSICTAB_ALL_SONGS(WidgetID.MUSICTAB_GROUP_ID, 3),
	MUSICTAB_SCROLLBAR(WidgetID.MUSICTAB_GROUP_ID, 4),
	MUSICTAB_PLAYING(WidgetID.MUSICTAB_GROUP_ID, 5),
	MUSICTAB_CURRENT_SONG_NAME(WidgetID.MUSICTAB_GROUP_ID, 6),
	MUSICTAB_AUTO_BUTTON_LISTENER(WidgetID.MUSICTAB_GROUP_ID, 7),
	MUSICTAB_AUTO_BUTTON(WidgetID.MUSICTAB_GROUP_ID, 8),
	MUSICTAB_MANUAL_BUTTON_LISTENER(WidgetID.MUSICTAB_GROUP_ID, 9),
	MUSICTAB_MANUAL_BUTTON(WidgetID.MUSICTAB_GROUP_ID, 10),
	MUSICTAB_LOOP_BUTTON_LISTENER(WidgetID.MUSICTAB_GROUP_ID, 11),
	MUSICTAB_LOOP_BUTTON(WidgetID.MUSICTAB_GROUP_ID, 12),
	MUSICTAB_UNLOCKED_SONGS(WidgetID.MUSICTAB_GROUP_ID, 13),

	QUESTTAB_QUEST_TAB(WidgetID.QUESTTAB_GROUP_ID, WidgetID.QuestTab.QUEST_TAB),

	EQUIPMENT_MELEE_STRENGTH(WidgetID.EQUIPMENT_PAGE_GROUP_ID, WidgetID.EquipmentWidgetIdentifiers.MELEE_STRENGTH),
	EQUIPMENT_RANGED_STRENGTH(WidgetID.EQUIPMENT_PAGE_GROUP_ID, WidgetID.EquipmentWidgetIdentifiers.RANGED_STRENGTH),
	EQUIPMENT_MAGIC_DAMAGE(WidgetID.EQUIPMENT_PAGE_GROUP_ID, WidgetID.EquipmentWidgetIdentifiers.MAGIC_DAMAGE),
	EQUIP_YOUR_CHARACTER(WidgetID.EQUIPMENT_PAGE_GROUP_ID, WidgetID.EquipmentWidgetIdentifiers.EQUIP_YOUR_CHARACTER),

	BANK_PIN_TOP_LEFT_TEXT(WidgetID.BANK_PIN_GROUP_ID, WidgetID.BankPin.TOP_LEFT_TEXT),
	BANK_PIN_EXIT_BUTTON(WidgetID.BANK_PIN_GROUP_ID, WidgetID.BankPin.EXIT_BUTTON),
	BANK_PIN_FORGOT_BUTTON(WidgetID.BANK_PIN_GROUP_ID, WidgetID.BankPin.FORGOT_BUTTON),
	BANK_PIN_FIRST_ENTERED(WidgetID.BANK_PIN_GROUP_ID, WidgetID.BankPin.FIRST_ENTERED),
	BANK_PIN_SECOND_ENTERED(WidgetID.BANK_PIN_GROUP_ID, WidgetID.BankPin.SECOND_ENTERED),
	BANK_PIN_THIRD_ENTERED(WidgetID.BANK_PIN_GROUP_ID, WidgetID.BankPin.THIRD_ENTERED),
	BANK_PIN_FOURTH_ENTERED(WidgetID.BANK_PIN_GROUP_ID, WidgetID.BankPin.FOURTH_ENTERED),
	BANK_PIN_INSTRUCTION_TEXT(WidgetID.BANK_PIN_GROUP_ID, WidgetID.BankPin.INSTRUCTION_TEXT),
	BANK_PIN_1(WidgetID.BANK_PIN_GROUP_ID, WidgetID.BankPin.BUTTON_1),
	BANK_PIN_2(WidgetID.BANK_PIN_GROUP_ID, WidgetID.BankPin.BUTTON_2),
	BANK_PIN_3(WidgetID.BANK_PIN_GROUP_ID, WidgetID.BankPin.BUTTON_3),
	BANK_PIN_4(WidgetID.BANK_PIN_GROUP_ID, WidgetID.BankPin.BUTTON_4),
	BANK_PIN_5(WidgetID.BANK_PIN_GROUP_ID, WidgetID.BankPin.BUTTON_5),
	BANK_PIN_6(WidgetID.BANK_PIN_GROUP_ID, WidgetID.BankPin.BUTTON_6),
	BANK_PIN_7(WidgetID.BANK_PIN_GROUP_ID, WidgetID.BankPin.BUTTON_7),
	BANK_PIN_8(WidgetID.BANK_PIN_GROUP_ID, WidgetID.BankPin.BUTTON_8),
	BANK_PIN_9(WidgetID.BANK_PIN_GROUP_ID, WidgetID.BankPin.BUTTON_9),
	BANK_PIN_10(WidgetID.BANK_PIN_GROUP_ID, WidgetID.BankPin.BUTTON_10),

	BANK_TUTORIAL_CONTAINER(WidgetID.BANK_TUTORIAL_GROUP_ID, WidgetID.BankTutorial.CONTAINER),
	BANK_TUTORIAL_STEP_TEXT(WidgetID.BANK_TUTORIAL_GROUP_ID, WidgetID.BankTutorial.STEP_TEXT),
	BANK_TUTORIAL_STEP_PROGRESS_TEXT(WidgetID.BANK_TUTORIAL_GROUP_ID, WidgetID.BankTutorial.STEP_PROGRESS_TEXT),
	BANK_TUTORIAL_CLOSE_BUTTON_CONTAINER(WidgetID.BANK_TUTORIAL_GROUP_ID, WidgetID.BankTutorial.CLOSE_BUTTON_CONTAINER),
	BANK_TUTORIAL_PREVIOUS_BUTTON(WidgetID.BANK_TUTORIAL_GROUP_ID, WidgetID.BankTutorial.PREVIOUS_BUTTON),
	BANK_TUTORIAL_CONTINUE_BUTTON(WidgetID.BANK_TUTORIAL_GROUP_ID, WidgetID.BankTutorial.CONTINUE_BUTTON),

	JEWELLERY_BOX_DUEL_RING(WidgetID.JEWELLERY_BOX_GROUP_ID, WidgetID.JewelBox.DUEL_RING),
	JEWELLERY_BOX_GAME_NECK(WidgetID.JEWELLERY_BOX_GROUP_ID, WidgetID.JewelBox.GAME_NECK),
	JEWELLERY_BOX_COMB_BRAC(WidgetID.JEWELLERY_BOX_GROUP_ID, WidgetID.JewelBox.COMB_BRAC),
	JEWELLERY_BOX_SKIL_NECK(WidgetID.JEWELLERY_BOX_GROUP_ID, WidgetID.JewelBox.SKIL_NECK),
	JEWELLERY_BOX_RING_OFGP(WidgetID.JEWELLERY_BOX_GROUP_ID, WidgetID.JewelBox.RING_OFGP),
	JEWELLERY_BOX_AMUL_GLOR(WidgetID.JEWELLERY_BOX_GROUP_ID, WidgetID.JewelBox.AMUL_GLOR),
	OPTIONS_CAMERA_ZOOM_SLIDER_HANDLE(WidgetID.OPTIONS_GROUP_ID, WidgetID.Options.CAMERA_ZOOM_SLIDER_HANDLE),
	OPTIONS_MUSIC_SLIDER(WidgetID.OPTIONS_GROUP_ID, WidgetID.Options.MUSIC_SLIDER),
	OPTIONS_SOUND_EFFECT_SLIDER(WidgetID.OPTIONS_GROUP_ID, WidgetID.Options.SOUND_EFFECT_SLIDER),
	OPTIONS_AREA_SOUND_SLIDER(WidgetID.OPTIONS_GROUP_ID, WidgetID.Options.AREA_SOUND_SLIDER),

	TRADING_WITH(WidgetID.PLAYER_TRADE_SCREEN_GROUP_ID, WidgetID.TradeScreen.FIRST_TRADING_WITH),
	SECOND_TRADING_WITH(WidgetID.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetID.TradeScreen.SECOND_TRADING_WITH),
	SECOND_TRADING_WITH_ACCEPT_BUTTON(WidgetID.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetID.TradeScreen.SECOND_ACCEPT_FUNC),
	SECOND_TRADING_WITH_ACCEPT_TEXT(WidgetID.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetID.TradeScreen.SECOND_ACCEPT_TEXT),
	SECOND_TRADING_WITH_DECLINE_BUTTON(WidgetID.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetID.TradeScreen.SECOND_DECLINE_FUNC),
	SECOND_TRADING_WITH_DECLINE_TEXT(WidgetID.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetID.TradeScreen.SECOND_DECLINE_TEXT),
	SECOND_TRADING_WITH_MY_OFFER(WidgetID.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetID.TradeScreen.SECOND_MY_OFFER),
	SECOND_TRADING_WITH_THEIR_OFFER(WidgetID.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetID.TradeScreen.SECOND_THEIR_OFFER),
	SECOND_TRADING_WITH_MY_ITEMS(WidgetID.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetID.TradeScreen.SECOND_MY_ITEMS),
	SECOND_TRADING_WITH_THEIR_ITEMS(WidgetID.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetID.TradeScreen.SECOND_THEIR_ITEMS),

	GAUNTLET_MAP(WidgetID.GAUNTLET_MAP_GROUP_ID, WidgetID.GauntletMap.CONTAINER),

	SHOP_ITEMS_CONTAINER(WidgetID.SHOP_GROUP_ID, WidgetID.Shop.ITEMS_CONTAINER),

	SET_DISPLAY_NAME_LAYER(WidgetID.SET_DISPLAY_NAME_GROUP_ID, WidgetID.SetDisplayName.LAYER),
	SET_DISPLAY_NAME_ENTER_NAME_INPUT(WidgetID.SET_DISPLAY_NAME_GROUP_ID, WidgetID.SetDisplayName.ENTER_NAME_INPUT),
	SET_DISPLAY_NAME_STATUS_TEXT(WidgetID.SET_DISPLAY_NAME_GROUP_ID, WidgetID.SetDisplayName.NAME_STATUS),
	SET_DISPLAY_NAME_SUGGESTIONS(WidgetID.SET_DISPLAY_NAME_GROUP_ID, WidgetID.SetDisplayName.NAME_SUGGESTIONS),
	SET_DISPLAY_NAME_LOOK_UP_NAME_BUTTON(WidgetID.SET_DISPLAY_NAME_GROUP_ID, WidgetID.SetDisplayName.LOOKUP_NAME_BUTTON),
	SET_DISPLAY_NAME_SET_NAME_BUTTON(WidgetID.SET_DISPLAY_NAME_GROUP_ID, WidgetID.SetDisplayName.SET_NAME_BUTTON),

	CHARACTER_CREATOR_LAYER(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.LAYER),
	CHARACTER_CREATOR_HEAD_LEFT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.HEAD_LEFT_BUTTON),
	CHARACTER_CREATOR_HEAD_RIGHT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.HEAD_RIGHT_BUTTON),
	CHARACTER_CREATOR_JAW_LEFT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.JAW_LEFT_BUTTON),
	CHARACTER_CREATOR_JAW_RIGHT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.JAW_RIGHT_BUTTON),
	CHARACTER_CREATOR_TORSO_LEFT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.TORSO_LEFT_BUTTON),
	CHARACTER_CREATOR_TORSO_RIGHT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.TORSO_RIGHT_BUTTON),
	CHARACTER_CREATOR_ARMS_LEFT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.ARMS_LEFT_BUTTON),
	CHARACTER_CREATOR_ARMS_RIGHT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.ARMS_RIGHT_BUTTON),
	CHARACTER_CREATOR_HANDS_LEFT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.HANDS_LEFT_BUTTON),
	CHARACTER_CREATOR_HANDS_RIGHT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.HANDS_RIGHT_BUTTON),
	CHARACTER_CREATOR_LEGS_LEFT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.LEGS_LEFT_BUTTON),
	CHARACTER_CREATOR_LEGS_RIGHT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.LEGS_RIGHT_BUTTON),
	CHARACTER_CREATOR_FEET_LEFT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.FEET_LEFT_BUTTON),
	CHARACTER_CREATOR_FEET_RIGHT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.FEET_RIGHT_BUTTON),
	CHARACTER_CREATOR_HAIR_COLOR_LEFT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.HAIR_COLOR_LEFT_BUTTON),
	CHARACTER_CREATOR_HAIR_COLOR_RIGHT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.HAIR_COLOR_RIGHT_BUTTON),
	CHARACTER_CREATOR_TORSO_COLOR_LEFT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.TORSO_COLOR_LEFT_BUTTON),
	CHARACTER_CREATOR_TORSO_COLOR_RIGHT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.TORSO_COLOR_RIGHT_BUTTON),
	CHARACTER_CREATOR_LEGS_COLOR_LEFT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.LEGS_COLOR_LEFT_BUTTON),
	CHARACTER_CREATOR_LEGS_COLOR_RIGHT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.LEGS_COLOR_RIGHT_BUTTON),
	CHARACTER_CREATOR_FEET_COLOR_LEFT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.FEET_COLOR_LEFT_BUTTON),
	CHARACTER_CREATOR_FEET_COLOR_RIGHT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.FEET_COLOR_RIGHT_BUTTON),
	CHARACTER_CREATOR_SKIN_COLOR_LEFT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.SKIN_COLOR_LEFT_BUTTON),
	CHARACTER_CREATOR_SKIN_COLOR_RIGHT_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.SKIN_COLOR_RIGHT_BUTTON),
	CHARACTER_CREATOR_GENDER_MALE_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.GENDER_MALE_BUTTON),
	CHARACTER_CREATOR_GENDER_FEMALE_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.GENDER_FEMALE_BUTTON),
	CHARACTER_CREATOR_CONFIRM_BUTTON(WidgetID.CHARACTER_CREATOR_GROUP_ID, WidgetID.CharacterCreator.CONFIRM_BUTTON),
	;

	private final int id;

	WidgetInfo(int id)
	{
		this.id = id;
	}

	WidgetInfo(int groupId, int childId)
	{
		this.id = (groupId << 16) | childId;
	}

	/**
	 * Gets the ID of the group-child pairing.
	 *
	 * @return the ID
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Gets the group ID of the pair.
	 *
	 * @return the group ID
	 */
	public int getGroupId()
	{
		return id >> 16;
	}

	/**
	 * Gets the ID of the child in the group.
	 *
	 * @return the child ID
	 */
	public int getChildId()
	{
		return id & 0xffff;
	}

	/**
	 * Gets the packed widget ID.
	 *
	 * @return the packed ID
	 */
	public int getPackedId()
	{
		return id;
	}

	/**
	 * Utility method that converts an ID returned by {@link #getId()} back
	 * to its group ID.
	 *
	 * @param id passed group-child ID
	 * @return the group ID
	 */
	public static int TO_GROUP(int id)
	{
		return id >>> 16;
	}

	/**
	 * Utility method that converts an ID returned by {@link #getId()} back
	 * to its child ID.
	 *
	 * @param id passed group-child ID
	 * @return the child ID
	 */
	public static int TO_CHILD(int id)
	{
		return id & 0xFFFF;
	}

	/**
	 * Packs the group and child IDs into a single integer.
	 *
	 * @param groupId the group ID
	 * @param childId the child ID
	 * @return the packed ID
	 */
	public static int PACK(int groupId, int childId)
	{
		return groupId << 16 | childId;
	}

}
