/*
 * Copyright (c) 2023, Kyle Escobar <https://github.com/runebox>
 * Copyright (c) 2023, Melxin <https://github.com/melxin>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package net.runelite.deob.deobfuscators.transformers;

import com.google.common.base.Stopwatch;
import lombok.AllArgsConstructor;
import lombok.Getter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import net.runelite.asm.ClassFile;
import net.runelite.asm.ClassGroup;
import net.runelite.asm.Field;
import net.runelite.asm.Method;
import net.runelite.asm.attributes.code.Instruction;
import net.runelite.asm.attributes.code.instruction.types.LVTInstruction;
import net.runelite.asm.attributes.code.instruction.types.PushConstantInstruction;
import net.runelite.asm.attributes.code.instructions.LDC;
import net.runelite.asm.signature.Signature;
import net.runelite.deob.Transformer;
import net.runelite.deob.deobfuscators.mapping.ParallelExecutorMapping;

public class BufferRenameTransformer implements Transformer
{
	private static final Logger logger = LoggerFactory.getLogger(BufferRenameTransformer.class);

	private final ParallelExecutorMapping mapping;
	private final ClassGroup namedGroup;

	public BufferRenameTransformer(ParallelExecutorMapping mapping, ClassGroup namedGroup)
	{
		this.mapping = mapping;
		this.namedGroup = namedGroup;
	}

	@Override
	public void transform(ClassGroup targetGroup)
	{
		Stopwatch stopWatch = Stopwatch.createStarted();

		ClassFile namedBufferCF = namedGroup.findClass("Buffer");
		ClassFile targetBufferCF = null;

		// Find buffer class
		outer:
		for (ClassFile classFile : targetGroup)
		{
			Method clinit = classFile.findMethod("<clinit>", new Signature("()V"));
			if (clinit == null) continue;
			if (clinit.getCode() == null) continue;
			if (clinit.getCode().getInstructions() == null) continue;
			for (Instruction insn : clinit.getCode().getInstructions().getInstructions())
			{
				if (insn instanceof LDC)
				{
					if (((LDC) insn).getConstant() instanceof Long && ((LDC) insn).getConstantAsLong() == -3932672073523589310L)
					{
						targetBufferCF = classFile;
						break outer;
					}
				}
			}
		}

		List<Method> namedMethods = namedBufferCF.getMethods().stream()
			.filter(m -> !m.isStatic())
			.filter(m -> !m.getName().equals("<clinit>"))
			.filter(m -> !m.getName().equals("<init>"))
			//.filter(m -> m.getCode() != null)
			.collect(Collectors.toList());

		List<Method> targetMethods = targetBufferCF.getMethods().stream()
			.filter(m -> !m.isStatic())
			.filter(m -> !m.getName().equals("<clinit>"))
			.filter(m -> !m.getName().equals("<init>"))
			//.filter(m -> m.getCode() != null)
			.collect(Collectors.toList());

		// Size mismatch
		if (targetMethods.size() != namedMethods.size())
		{
			logger.warn("targetMethodSize: {} != namedMethodSize: {}", targetMethods.size(), namedMethods.size());
			//return;
		}

		// Named methods matches hard coded methods?
		int namedMethodsCount = (int) namedMethods.stream().filter(m -> !m.getName().startsWith("method")).count();
		int targetMethodsCountHardcoded = TargetBufferMethods.TARGET_BUFFER_METHODS.keySet().size();
		if (namedMethodsCount != targetMethodsCountHardcoded)
		{
			List<String> newMappedMethods = namedMethods.stream()
				.filter(m -> !m.getName().startsWith("method") && !TargetBufferMethods.TARGET_BUFFER_METHODS.containsKey(m.getName()))
				.map(Method::getName)
				.collect(Collectors.toList());

			logger.error("Add the newly mapped methods: {}", newMappedMethods.toString());
		}

		// Print
		//printBufferMethods(namedMethods, targetMethods);
		//System.exit(0);

		// Remove existing buffer mapping
		//this.mapping.getMap().keySet().removeIf(k -> k.toString().startsWith("Buffer.") || k.toString().contains(" Buffer."));
		this.mapping.getMapInstance().keySet().removeIf(k -> k.toString().startsWith("Buffer.") || k.toString().contains(" Buffer."));

		// Map class
		mapping.map(null, namedBufferCF, targetBufferCF);

		// Map fields
		List<Field> namedFields = namedBufferCF.getFields();
		List<Field> targetFields = targetBufferCF.getFields();
		for (int i = 0; i < namedFields.size(); i++)
		{
			Field namedField = namedFields.get(i);
			Field targetField = targetFields.get(i);
			if (namedField.getName().startsWith("field"))
			{
				continue;
			}
			logger.info("Mapped field: {} -> {}", targetField.getName(), namedField.getName());
			mapping.map(null, namedField, targetField);
		}

		// Map methods
		Map<String, Method> namedMethodsM = namedMethods.stream()
			.collect(Collectors.toMap(Method::getName, Function.identity()));
		for (Method targetMethod : targetMethods)
		{
			List<String> targetIns = targetMethod.getCode().getInstructions().getInstructions().stream()
				.map(this::getInstructionAsString)
				.collect(Collectors.toList());

			for (Map.Entry<String, TargetBufferMethods> entry : TargetBufferMethods.TARGET_BUFFER_METHODS.entrySet())
			{
				String name = entry.getKey();
				List<List<String>> comparingIns = entry.getValue().getInstructions();

				if (comparingIns.stream().anyMatch(targetIns::equals))
				{
					Method namedMethod = namedMethodsM.get(name);
					if (namedMethod != null)
					{
						mapping.map(null, namedMethod, targetMethod);
						logger.info("Mapped method: {} -> {}", targetMethod.getName(), name);
					}
					else
					{
						logger.error("Named method: {} is not present!", name);
					}
					break;
				}
			}
		}

		namedMethods.stream()
			.filter(m -> !m.getName().startsWith("method") && !mapping.getMap().containsKey(m))
			.forEach(m -> logger.error("Failed to map: {}", m.getName()));

		logger.warn("Buffer rename order might have been incorrect verify manually!");
		logger.info("Took: {}", stopWatch);
	}

	private void printBufferMethods(List<Method> namedMethods, List<Method> targetMethods)
	{
		if (namedMethods.size() != targetMethods.size())
		{
			return;
		}

		for (int i = 0; i < Math.max(namedMethods.size(), targetMethods.size()); i++)
		{
			Method namedMethod = namedMethods.get(i);
			if (namedMethod.getName().startsWith("method"))
			{
				continue;
			}

			Method targetMethod = targetMethods.get(i);
			List<String> targetIns = targetMethod.getCode().getInstructions().getInstructions().stream()
				.map(this::getInstructionAsString)
				.collect(Collectors.toList());

			System.out.println(namedMethod.getName());
			for (int j = 0; j < targetIns.size(); j++)
			{
				if (j < targetIns.size() - 1)
				{
					System.out.println('"' + targetIns.get(j) + '"' + ",");
				}
				else
				{
					System.out.println('"' + targetIns.get(j) + '"');
				}
			}

			TargetBufferMethods targetBufferMethod = TargetBufferMethods.TARGET_BUFFER_METHODS.get(namedMethod.getName());
			if (targetBufferMethod != null && TargetBufferMethods.TARGET_BUFFER_METHODS.get(namedMethod.getName()).getInstructions().stream().anyMatch(targetIns::equals))
			{
				System.out.println("Match: " + namedMethod.getName());
			}
			else
			{
				System.out.println("Ins does not match: " + namedMethod.getName());
			}

			System.out.println("\n");
		}
	}

	private String getInstructionAsString(Instruction in)
	{
		if (in instanceof PushConstantInstruction)
		{
			return in.toString();
		}
		else if (in instanceof LVTInstruction)
		{
			return in.getType() + " " + ((LVTInstruction) in).getVariableIndex();
		}
		return in.getType().toString();
	}

	@Getter
	@AllArgsConstructor
	private enum TargetBufferMethods
	{
		RELEASE_ARRAY("releaseArray", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ACONST_NULL",
				"IF_ACMPEQ",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"INVOKESTATIC",
				"NOP",
				"ALOAD 0",
				"ACONST_NULL",
				"PUTFIELD",
				"NOP",
				"RETURN"),
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"IFNULL",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"INVOKESTATIC",
				"NOP",
				"ALOAD 0",
				"ACONST_NULL",
				"PUTFIELD",
				"NOP",
				"RETURN"),
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"IFNULL",
				"ALOAD 0",
				"GETFIELD",
				"INVOKESTATIC",
				"NOP",
				"ALOAD 0",
				"ACONST_NULL",
				"PUTFIELD",
				"NOP",
				"RETURN")
		)
		),

		WRITE_BYTE("writeByte", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN")
		)
		),

		WRITE_SHORT("writeShort", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"bipush 8",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN")
		)
		),

		WRITE_MEDIUM("writeMedium", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"bipush 16",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"bipush 8",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN")
		)
		),

		WRITE_INT("writeInt", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"bipush 24",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"bipush 16",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"bipush 8",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN")
		)
		),

		WRITE_LONG_MEDIUM("writeLongMedium", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"LLOAD 1",
				"bipush 40",
				"LSHR",
				"L2I",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"LLOAD 1",
				"bipush 32",
				"LSHR",
				"L2I",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"LLOAD 1",
				"bipush 24",
				"LSHR",
				"L2I",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"LLOAD 1",
				"bipush 16",
				"LSHR",
				"L2I",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"LLOAD 1",
				"bipush 8",
				"LSHR",
				"L2I",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"LLOAD 1",
				"L2I",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN")
		)
		),

		WRITE_LONG("writeLong", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"LLOAD 1",
				"bipush 56",
				"LSHR",
				"L2I",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"LLOAD 1",
				"bipush 48",
				"LSHR",
				"L2I",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"LLOAD 1",
				"bipush 40",
				"LSHR",
				"L2I",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"LLOAD 1",
				"bipush 32",
				"LSHR",
				"L2I",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"LLOAD 1",
				"bipush 24",
				"LSHR",
				"L2I",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"LLOAD 1",
				"bipush 16",
				"LSHR",
				"L2I",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"LLOAD 1",
				"bipush 8",
				"LSHR",
				"L2I",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"LLOAD 1",
				"L2I",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN")
		)
		),

		WRITE_BOOLEAN("writeBoolean", List.of(
			List.of("NOP",
				"ALOAD 0",
				"ILOAD 1",
				"IFEQ",
				"GOTO",
				"NOP",
				"ldc 1",
				"GOTO",
				"NOP",
				"ldc 0",
				"NOP",
				"INVOKEVIRTUAL",
				"NOP",
				"RETURN")
		)
		),

		WRITE_STRING_CP_1252_NULL_TERMINATED("writeStringCp1252NullTerminated", List.of(
			List.of("NOP",
				"ALOAD 1",
				"ldc 0",
				"INVOKEVIRTUAL",
				"ISTORE 2",
				"NOP",
				"ILOAD 2",
				"IFLT",
				"GOTO",
				"NOP",
				"NEW",
				"DUP",
				"ldc ",
				"INVOKESPECIAL",
				"ATHROW",
				"NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ALOAD 1",
				"ldc 0",
				"ALOAD 1",
				"INVOKEVIRTUAL",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"INVOKESTATIC",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ldc 0",
				"BASTORE",
				"NOP",
				"RETURN"),
			List.of("NOP",
				"ALOAD 1",
				"ldc 0",
				"INVOKEVIRTUAL",
				"ISTORE 2",
				"NOP",
				"ILOAD 2",
				"IFLT",
				"NEW",
				"DUP",
				"ldc ",
				"INVOKESPECIAL",
				"ATHROW",
				"NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ALOAD 1",
				"ldc 0",
				"ALOAD 1",
				"INVOKEVIRTUAL",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"INVOKESTATIC",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ldc 0",
				"BASTORE",
				"NOP",
				"RETURN")
		)
		),

		WRITE_STRING_CP_1252_NULL_CIRCUM_FIXED("writeStringCp1252NullCircumfixed", List.of(
			List.of("NOP",
				"ALOAD 1",
				"ldc 0",
				"INVOKEVIRTUAL",
				"ISTORE 2",
				"NOP",
				"ILOAD 2",
				"IFLT",
				"GOTO",
				"NOP",
				"NEW",
				"DUP",
				"ldc ",
				"INVOKESPECIAL",
				"ATHROW",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ldc 0",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ALOAD 1",
				"ldc 0",
				"ALOAD 1",
				"INVOKEVIRTUAL",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"INVOKESTATIC",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ldc 0",
				"BASTORE",
				"NOP",
				"RETURN")
		)
		),

		WRITE_CESU8("writeCESU8", List.of(
			List.of("NOP",
				"ALOAD 1",
				"INVOKEINTERFACE",
				"ISTORE 3",
				"NOP",
				"ldc 0",
				"ISTORE 4",
				"NOP",
				"ldc 0",
				"ISTORE 5",
				"NOP",
				"ILOAD 5",
				"ILOAD 3",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ILOAD 4",
				"ISTORE 2",
				"NOP",
				"ILOAD 2",
				"ISTORE 3",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ldc 0",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"ILOAD 3",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 1",
				"INVOKESTATIC",
				"IADD",
				"PUTFIELD",
				"NOP",
				"RETURN",
				"NOP",
				"ALOAD 1",
				"ILOAD 5",
				"INVOKEINTERFACE",
				"ISTORE 6",
				"NOP",
				"ILOAD 6",
				"bipush 127",
				"IF_ICMPGT",
				"GOTO",
				"NOP",
				"IINC 4",
				"GOTO",
				"NOP",
				"ILOAD 6",
				"sipush 2047",
				"IF_ICMPGT",
				"GOTO",
				"NOP",
				"IINC 4",
				"GOTO",
				"NOP",
				"IINC 4",
				"NOP",
				"IINC 5",
				"GOTO"),
			List.of("NOP",
				"ALOAD 1",
				"INVOKESTATIC",
				"ISTORE 2",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ldc 0",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"ILOAD 2",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 1",
				"INVOKESTATIC",
				"IADD",
				"PUTFIELD",
				"NOP",
				"RETURN"),
			List.of("NOP",
				"ALOAD 1",
				"INVOKEINTERFACE",
				"ISTORE 3",
				"NOP",
				"ldc 0",
				"ISTORE 4",
				"NOP",
				"ldc 0",
				"ISTORE 5",
				"NOP",
				"ILOAD 5",
				"ILOAD 3",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ILOAD 4",
				"ISTORE 2",
				"NOP",
				"ILOAD 2",
				"ISTORE 3",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ldc 0",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"ILOAD 3",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ISTORE 4",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ASTORE 6",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ISTORE 7",
				"NOP",
				"ALOAD 1",
				"INVOKEINTERFACE",
				"ISTORE 8",
				"NOP",
				"ILOAD 7",
				"ISTORE 9",
				"NOP",
				"ldc 0",
				"ISTORE 10",
				"NOP",
				"ILOAD 10",
				"ILOAD 8",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ILOAD 9",
				"ILOAD 7",
				"ISUB",
				"ISTORE 5",
				"NOP",
				"ALOAD 0",
				"ILOAD 4",
				"ILOAD 5",
				"IADD",
				"PUTFIELD",
				"NOP",
				"RETURN",
				"NOP",
				"ALOAD 1",
				"ILOAD 10",
				"INVOKEINTERFACE",
				"ISTORE 11",
				"NOP",
				"ILOAD 11",
				"bipush 127",
				"IF_ICMPGT",
				"GOTO",
				"NOP",
				"ILOAD 11",
				"sipush 2047",
				"IF_ICMPGT",
				"GOTO",
				"NOP",
				"ALOAD 6",
				"ILOAD 9",
				"IINC 9",
				"sipush 224",
				"ILOAD 11",
				"bipush 12",
				"ISHR",
				"IOR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 6",
				"ILOAD 9",
				"IINC 9",
				"sipush 128",
				"ILOAD 11",
				"bipush 6",
				"ISHR",
				"bipush 63",
				"IAND",
				"IOR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 6",
				"ILOAD 9",
				"IINC 9",
				"sipush 128",
				"ILOAD 11",
				"bipush 63",
				"IAND",
				"IOR",
				"I2B",
				"BASTORE",
				"GOTO",
				"NOP",
				"ALOAD 6",
				"ILOAD 9",
				"IINC 9",
				"sipush 192",
				"ILOAD 11",
				"bipush 6",
				"ISHR",
				"IOR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 6",
				"ILOAD 9",
				"IINC 9",
				"sipush 128",
				"ILOAD 11",
				"bipush 63",
				"IAND",
				"IOR",
				"I2B",
				"BASTORE",
				"GOTO",
				"NOP",
				"ALOAD 6",
				"ILOAD 9",
				"IINC 9",
				"ILOAD 11",
				"I2B",
				"BASTORE",
				"NOP",
				"IINC 10",
				"GOTO",
				"NOP",
				"ALOAD 1",
				"ILOAD 5",
				"INVOKEINTERFACE",
				"ISTORE 12",
				"NOP",
				"ILOAD 12",
				"bipush 127",
				"IF_ICMPGT",
				"GOTO",
				"NOP",
				"IINC 4",
				"GOTO",
				"NOP",
				"ILOAD 12",
				"sipush 2047",
				"IF_ICMPGT",
				"GOTO",
				"NOP",
				"IINC 4",
				"GOTO",
				"NOP",
				"IINC 4",
				"NOP",
				"IINC 5",
				"GOTO")
		)
		),

		WRITE_BYTES("writeBytes", List.of(
			List.of("NOP",
				"ILOAD 2",
				"ISTORE 4",
				"NOP",
				"ILOAD 4",
				"ILOAD 3",
				"ILOAD 2",
				"IADD",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ALOAD 1",
				"ILOAD 4",
				"BALOAD",
				"BASTORE",
				"IINC 4",
				"GOTO",
				"NOP",
				"RETURN"),
			List.of("NOP",
				"ILOAD 2",
				"ISTORE 4",
				"NOP",
				"ILOAD 4",
				"ILOAD 3",
				"ILOAD 2",
				"IADD",
				"IF_ICMPGE",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ALOAD 1",
				"ILOAD 4",
				"BALOAD",
				"BASTORE",
				"IINC 4",
				"GOTO",
				"NOP",
				"RETURN")
		)
		),

		WRITE_BUFFER("writeBuffer", List.of(
			List.of("NOP",
				"ALOAD 0",
				"ALOAD 1",
				"GETFIELD",
				"ldc 0",
				"ALOAD 1",
				"GETFIELD",
				"INVOKEVIRTUAL",
				"NOP",
				"RETURN")
		)
		),

		WRITE_LENGTH_INT("writeLengthInt", List.of(
			List.of("NOP",
				"ILOAD 1",
				"IFGE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 1",
				"ISUB",
				"ldc 4",
				"ISUB",
				"ILOAD 1",
				"bipush 24",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 1",
				"ISUB",
				"ldc 3",
				"ISUB",
				"ILOAD 1",
				"bipush 16",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 1",
				"ISUB",
				"ldc 2",
				"ISUB",
				"ILOAD 1",
				"bipush 8",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 1",
				"ISUB",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN",
				"NOP",
				"NEW",
				"DUP",
				"INVOKESPECIAL",
				"ATHROW")
		)
		),

		WRITE_LENGTH_SHORT("writeLengthShort", List.of(
			List.of("NOP",
				"ILOAD 1",
				"IFLT",
				"ILOAD 1",
				"ldc 65535",
				"IF_ICMPLE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 1",
				"ISUB",
				"ldc 2",
				"ISUB",
				"ILOAD 1",
				"bipush 8",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 1",
				"ISUB",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN",
				"NOP",
				"NEW",
				"DUP",
				"INVOKESPECIAL",
				"ATHROW"),
			List.of("NOP",
				"ILOAD 1",
				"IFLT",
				"GOTO",
				"NOP",
				"ILOAD 1",
				"ldc 65535",
				"IF_ICMPLE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 1",
				"ISUB",
				"ldc 2",
				"ISUB",
				"ILOAD 1",
				"bipush 8",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 1",
				"ISUB",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN",
				"NOP",
				"NEW",
				"DUP",
				"INVOKESPECIAL",
				"ATHROW")
		)
		),

		WRITE_LENGTH_BYTE("writeLengthByte", List.of(
			List.of("NOP",
				"ILOAD 1",
				"IFLT",
				"GOTO",
				"NOP",
				"ILOAD 1",
				"sipush 255",
				"IF_ICMPLE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 1",
				"ISUB",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN",
				"NOP",
				"NEW",
				"DUP",
				"INVOKESPECIAL",
				"ATHROW"),
			List.of("NOP",
				"ILOAD 1",
				"IFLT",
				"ILOAD 1",
				"sipush 255",
				"IF_ICMPLE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 1",
				"ISUB",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN",
				"NOP",
				"NEW",
				"DUP",
				"INVOKESPECIAL",
				"ATHROW")
		)
		),

		WRITE_SMART_BYTE_SHORT("writeSmartByteShort", List.of(
			List.of("NOP",
				"ILOAD 1",
				"IFLT",
				"ILOAD 1",
				"sipush 128",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ILOAD 1",
				"IFLT",
				"GOTO",
				"NOP",
				"ILOAD 1",
				"ldc 32768",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"ILOAD 1",
				"ldc 32768",
				"IADD",
				"INVOKEVIRTUAL",
				"NOP",
				"RETURN",
				"NOP",
				"NEW",
				"DUP",
				"INVOKESPECIAL",
				"ATHROW",
				"NOP",
				"ALOAD 0",
				"ILOAD 1",
				"INVOKEVIRTUAL",
				"NOP",
				"RETURN"),
			List.of("NOP",
				"ILOAD 1",
				"IFLT",
				"ILOAD 1",
				"sipush 128",
				"IF_ICMPGE",
				"NOP",
				"ALOAD 0",
				"ILOAD 1",
				"INVOKEVIRTUAL",
				"NOP",
				"RETURN",
				"NOP",
				"ILOAD 1",
				"IFLT",
				"GOTO",
				"NOP",
				"ILOAD 1",
				"ldc 32768",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"ILOAD 1",
				"ldc 32768",
				"IADD",
				"INVOKEVIRTUAL",
				"NOP",
				"RETURN",
				"NOP",
				"NEW",
				"DUP",
				"INVOKESPECIAL",
				"ATHROW")
		)
		),

		WRITE_VAR_INT("writeVarInt", List.of(
			List.of("NOP",
				"ILOAD 1",
				"bipush -128",
				"IAND",
				"IFEQ",
				"GOTO",
				"NOP",
				"ILOAD 1",
				"sipush -16384",
				"IAND",
				"IFEQ",
				"GOTO",
				"NOP",
				"ILOAD 1",
				"ldc -2097152",
				"IAND",
				"ldc 0",
				"IF_ICMPEQ",
				"GOTO",
				"NOP",
				"ILOAD 1",
				"ldc -268435456",
				"IAND",
				"IFEQ",
				"ALOAD 0",
				"ILOAD 1",
				"bipush 28",
				"IUSHR",
				"sipush 128",
				"IOR",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 1",
				"bipush 21",
				"IUSHR",
				"sipush 128",
				"IOR",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 1",
				"bipush 14",
				"IUSHR",
				"sipush 128",
				"IOR",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 1",
				"bipush 7",
				"IUSHR",
				"sipush 128",
				"IOR",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 1",
				"bipush 127",
				"IAND",
				"INVOKEVIRTUAL",
				"NOP",
				"RETURN"),
			List.of("NOP",
				"ILOAD 1",
				"bipush -128",
				"IAND",
				"ldc 0",
				"IF_ICMPEQ",
				"NOP",
				"ILOAD 1",
				"sipush -16384",
				"IAND",
				"ldc 0",
				"IF_ICMPEQ",
				"GOTO",
				"NOP",
				"ILOAD 1",
				"ldc -2097152",
				"IAND",
				"IFEQ",
				"NOP",
				"ILOAD 1",
				"ldc -268435456",
				"IAND",
				"IFEQ",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"ILOAD 1",
				"bipush 28",
				"IUSHR",
				"sipush 128",
				"IOR",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 1",
				"bipush 21",
				"IUSHR",
				"sipush 128",
				"IOR",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 1",
				"bipush 14",
				"IUSHR",
				"sipush 128",
				"IOR",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 1",
				"bipush 7",
				"IUSHR",
				"sipush 128",
				"IOR",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 1",
				"bipush 127",
				"IAND",
				"INVOKEVIRTUAL",
				"NOP",
				"RETURN"),
			List.of("NOP",
				"ILOAD 1",
				"bipush -128",
				"IAND",
				"ldc 0",
				"IF_ICMPEQ",
				"GOTO",
				"NOP",
				"ILOAD 1",
				"sipush -16384",
				"IAND",
				"IFEQ",
				"GOTO",
				"NOP",
				"ILOAD 1",
				"ldc -2097152",
				"IAND",
				"ldc 0",
				"IF_ICMPEQ",
				"GOTO",
				"NOP",
				"ILOAD 1",
				"ldc -268435456",
				"IAND",
				"ldc 0",
				"IF_ICMPEQ",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"ILOAD 1",
				"bipush 28",
				"IUSHR",
				"sipush 128",
				"IOR",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 1",
				"bipush 21",
				"IUSHR",
				"sipush 128",
				"IOR",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 1",
				"bipush 14",
				"IUSHR",
				"sipush 128",
				"IOR",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 1",
				"bipush 7",
				"IUSHR",
				"sipush 128",
				"IOR",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 1",
				"bipush 127",
				"IAND",
				"INVOKEVIRTUAL",
				"NOP",
				"RETURN")
		)
		),

		READ_UNSIGNED_BYTE("readUnsignedByte", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"IRETURN")
		)
		),

		READ_BYTE("readByte", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"IRETURN")
		)
		),

		READ_UNSIGNED_SHORT("readUnsignedShort", List.of(
			List.of("NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 2",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 2",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 8",
				"ISHL",
				"IADD",
				"IRETURN")
		)
		),

		READ_SHORT("readShort", List.of(
			List.of("NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 2",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 2",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 8",
				"ISHL",
				"IADD",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"sipush 32767",
				"IF_ICMPLE",
				"GOTO",
				"NOP",
				"ILOAD 1",
				"ldc 65536",
				"ISUB",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"IRETURN")
		)
		),

		READ_MEDIUM("readMedium", List.of(
			List.of("NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 3",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 3",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 16",
				"ISHL",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"IADD",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 2",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 8",
				"ISHL",
				"IADD",
				"IRETURN")
		)
		),

		READ_INT("readInt", List.of(
			List.of("NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 4",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 3",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 16",
				"ISHL",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"IADD",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 2",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 8",
				"ISHL",
				"IADD",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 4",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 24",
				"ISHL",
				"IADD",
				"IRETURN")
		)
		),

		READ_LONG("readLong", List.of(
			List.of("NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"I2L",
				"ldc 4294967295",
				"LAND",
				"LSTORE 1",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"I2L",
				"ldc 4294967295",
				"LAND",
				"LSTORE 3",
				"NOP",
				"LLOAD 3",
				"LLOAD 1",
				"bipush 32",
				"LSHL",
				"LADD",
				"LRETURN"),
			List.of("NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"I2L",
				"ldc 4294967295",
				"LAND",
				"LSTORE 1",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"I2L",
				"ldc 4294967295",
				"LAND",
				"LSTORE 3",
				"NOP",
				"LLOAD 1",
				"bipush 32",
				"LSHL",
				"LLOAD 3",
				"LADD",
				"LRETURN")
		)
		),

		READ_BOOLEAN("readBoolean", List.of(
			List.of("NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ldc 1",
				"IAND",
				"ldc 1",
				"IF_ICMPNE",
				"GOTO",
				"NOP",
				"ldc 1",
				"GOTO",
				"NOP",
				"ldc 0",
				"NOP",
				"IRETURN")
		)
		),

		READ_STRING_CP_1252_NULL_TERMINATED_OR_NULL("readStringCp1252NullTerminatedOrNull", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"BALOAD",
				"IFNE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ARETURN",
				"NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ACONST_NULL",
				"ARETURN"),
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"BALOAD",
				"ldc 0",
				"IF_ICMPNE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ARETURN",
				"NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ACONST_NULL",
				"ARETURN")
		)
		),

		READ_STRING_CP_1252_NULL_TERMINATED("readStringCp1252NullTerminated", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ISTORE 1",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"IFEQ",
				"GOTO",
				"NOP",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 1",
				"ISUB",
				"ldc 1",
				"ISUB",
				"ISTORE 2",
				"NOP",
				"ILOAD 2",
				"IFNE",
				"GOTO",
				"NOP",
				"ldc ",
				"ARETURN",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 1",
				"ILOAD 2",
				"INVOKESTATIC",
				"ARETURN"),
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ISTORE 1",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"IFEQ",
				"GOTO",
				"NOP",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 1",
				"ISUB",
				"ldc 1",
				"ISUB",
				"ISTORE 2",
				"NOP",
				"ILOAD 2",
				"ldc 0",
				"IF_ICMPNE",
				"GOTO",
				"NOP",
				"ldc ",
				"ARETURN",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 1",
				"ILOAD 2",
				"INVOKESTATIC",
				"ARETURN")
		)
		),

		READ_STRING_CP_1252_NULL_CIRCUM_FIXED("readStringCp1252NullCircumfixed", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"IFEQ",
				"GOTO",
				"NOP",
				"NEW",
				"DUP",
				"ldc ",
				"INVOKESPECIAL",
				"ATHROW",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ISTORE 2",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"IFEQ",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 2",
				"ISUB",
				"ldc 1",
				"ISUB",
				"ISTORE 3",
				"NOP",
				"ILOAD 3",
				"ldc 0",
				"IF_ICMPNE",
				"ldc ",
				"ARETURN",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 2",
				"ILOAD 3",
				"INVOKESTATIC",
				"ARETURN"),
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"ldc 0",
				"IF_ICMPEQ",
				"GOTO",
				"NOP",
				"NEW",
				"DUP",
				"ldc ",
				"INVOKESPECIAL",
				"ATHROW",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ISTORE 2",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"IFEQ",
				"GOTO",
				"NOP",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 2",
				"ISUB",
				"ldc 1",
				"ISUB",
				"ISTORE 3",
				"NOP",
				"ILOAD 3",
				"ldc 0",
				"IF_ICMPNE",
				"GOTO",
				"NOP",
				"ldc ",
				"ARETURN",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 2",
				"ILOAD 3",
				"INVOKESTATIC",
				"ARETURN"),
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"ldc 0",
				"IF_ICMPEQ",
				"NEW",
				"DUP",
				"ldc ",
				"INVOKESPECIAL",
				"ATHROW",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ISTORE 2",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"IFEQ",
				"GOTO",
				"NOP",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 2",
				"ISUB",
				"ldc 1",
				"ISUB",
				"ISTORE 3",
				"NOP",
				"ILOAD 3",
				"IFNE",
				"GOTO",
				"NOP",
				"ldc ",
				"ARETURN",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 2",
				"ILOAD 3",
				"INVOKESTATIC",
				"ARETURN")
		)
		),

		READ_CESU8("readCESU8", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"ldc 0",
				"IF_ICMPEQ",
				"GOTO",
				"NOP",
				"NEW",
				"DUP",
				"ldc ",
				"INVOKESPECIAL",
				"ATHROW",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 2",
				"NOP",
				"ILOAD 2",
				"ALOAD 0",
				"GETFIELD",
				"IADD",
				"ALOAD 0",
				"GETFIELD",
				"ARRAYLENGTH",
				"IF_ICMPLE",
				"GOTO",
				"NOP",
				"NEW",
				"DUP",
				"ldc ",
				"INVOKESPECIAL",
				"ATHROW",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ASTORE 4",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ISTORE 5",
				"NOP",
				"ILOAD 2",
				"NEWARRAY",
				"ASTORE 6",
				"NOP",
				"ldc 0",
				"ISTORE 7",
				"NOP",
				"ILOAD 5",
				"ISTORE 8",
				"NOP",
				"ILOAD 5",
				"ILOAD 2",
				"IADD",
				"ISTORE 9",
				"NOP",
				"ILOAD 8",
				"ILOAD 9",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"NEW",
				"DUP",
				"ALOAD 6",
				"ldc 0",
				"ILOAD 7",
				"INVOKESPECIAL",
				"ASTORE 3",
				"NOP",
				"ALOAD 3",
				"ASTORE 6",
				"NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ILOAD 2",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 6",
				"ARETURN",
				"NOP",
				"ALOAD 4",
				"ILOAD 8",
				"IINC 8",
				"BALOAD",
				"sipush 255",
				"IAND",
				"ISTORE 10",
				"NOP",
				"ILOAD 10",
				"sipush 128",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ILOAD 10",
				"sipush 192",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ILOAD 10",
				"sipush 224",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ILOAD 10",
				"sipush 240",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ILOAD 10",
				"sipush 248",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ILOAD 8",
				"ldc 2",
				"IADD",
				"ILOAD 9",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ALOAD 4",
				"ILOAD 8",
				"BALOAD",
				"sipush 192",
				"IAND",
				"sipush 128",
				"IF_ICMPNE",
				"GOTO",
				"NOP",
				"ALOAD 4",
				"ILOAD 8",
				"ldc 1",
				"IADD",
				"BALOAD",
				"sipush 192",
				"IAND",
				"sipush 128",
				"IF_ICMPNE",
				"ALOAD 4",
				"ILOAD 8",
				"ldc 2",
				"IADD",
				"BALOAD",
				"sipush 192",
				"IAND",
				"sipush 128",
				"IF_ICMPNE",
				"NOP",
				"ILOAD 10",
				"bipush 7",
				"IAND",
				"bipush 18",
				"ISHL",
				"ALOAD 4",
				"ILOAD 8",
				"IINC 8",
				"BALOAD",
				"bipush 63",
				"IAND",
				"bipush 12",
				"ISHL",
				"IOR",
				"ALOAD 4",
				"ILOAD 8",
				"IINC 8",
				"BALOAD",
				"bipush 63",
				"IAND",
				"bipush 6",
				"ISHL",
				"IOR",
				"ALOAD 4",
				"ILOAD 8",
				"IINC 8",
				"BALOAD",
				"bipush 63",
				"IAND",
				"IOR",
				"ISTORE 11",
				"NOP",
				"ILOAD 11",
				"ldc 65536",
				"IF_ICMPLT",
				"GOTO",
				"NOP",
				"ILOAD 11",
				"ldc 1114111",
				"IF_ICMPLE",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ILOAD 8",
				"ldc 1",
				"IADD",
				"ILOAD 9",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ALOAD 4",
				"ILOAD 8",
				"BALOAD",
				"sipush 192",
				"IAND",
				"sipush 128",
				"IF_ICMPNE",
				"GOTO",
				"NOP",
				"ALOAD 4",
				"ILOAD 8",
				"ldc 1",
				"IADD",
				"BALOAD",
				"sipush 192",
				"IAND",
				"sipush 128",
				"IF_ICMPNE",
				"GOTO",
				"NOP",
				"ILOAD 10",
				"bipush 15",
				"IAND",
				"bipush 12",
				"ISHL",
				"ALOAD 4",
				"ILOAD 8",
				"IINC 8",
				"BALOAD",
				"bipush 63",
				"IAND",
				"bipush 6",
				"ISHL",
				"IOR",
				"ALOAD 4",
				"ILOAD 8",
				"IINC 8",
				"BALOAD",
				"bipush 63",
				"IAND",
				"IOR",
				"ISTORE 11",
				"NOP",
				"ILOAD 11",
				"sipush 2048",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ILOAD 8",
				"ILOAD 9",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ALOAD 4",
				"ILOAD 8",
				"BALOAD",
				"sipush 192",
				"IAND",
				"sipush 128",
				"IF_ICMPNE",
				"GOTO",
				"NOP",
				"ILOAD 10",
				"bipush 31",
				"IAND",
				"bipush 6",
				"ISHL",
				"ALOAD 4",
				"ILOAD 8",
				"IINC 8",
				"BALOAD",
				"bipush 63",
				"IAND",
				"IOR",
				"ISTORE 11",
				"NOP",
				"ILOAD 11",
				"sipush 128",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ILOAD 10",
				"IFNE",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ILOAD 10",
				"ISTORE 11",
				"NOP",
				"ALOAD 6",
				"ILOAD 7",
				"IINC 7",
				"ILOAD 11",
				"I2C",
				"CASTORE",
				"NOP",
				"GOTO"),
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"IFEQ",
				"GOTO",
				"NOP",
				"NEW",
				"DUP",
				"ldc ",
				"INVOKESPECIAL",
				"ATHROW",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 2",
				"NOP",
				"ILOAD 2",
				"ALOAD 0",
				"GETFIELD",
				"IADD",
				"ALOAD 0",
				"GETFIELD",
				"ARRAYLENGTH",
				"IF_ICMPLE",
				"GOTO",
				"NOP",
				"NEW",
				"DUP",
				"ldc ",
				"INVOKESPECIAL",
				"ATHROW",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ASTORE 4",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ISTORE 5",
				"NOP",
				"ILOAD 2",
				"NEWARRAY",
				"ASTORE 6",
				"NOP",
				"ldc 0",
				"ISTORE 7",
				"NOP",
				"ILOAD 5",
				"ISTORE 8",
				"NOP",
				"ILOAD 2",
				"ILOAD 5",
				"IADD",
				"ISTORE 9",
				"NOP",
				"ILOAD 8",
				"ILOAD 9",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"NEW",
				"DUP",
				"ALOAD 6",
				"ldc 0",
				"ILOAD 7",
				"INVOKESPECIAL",
				"ASTORE 3",
				"NOP",
				"ALOAD 3",
				"ASTORE 6",
				"NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ILOAD 2",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 6",
				"ARETURN",
				"NOP",
				"ALOAD 4",
				"ILOAD 8",
				"IINC 8",
				"BALOAD",
				"sipush 255",
				"IAND",
				"ISTORE 10",
				"NOP",
				"ILOAD 10",
				"sipush 128",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ILOAD 10",
				"sipush 192",
				"IF_ICMPGE",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ILOAD 10",
				"sipush 224",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ILOAD 10",
				"sipush 240",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ILOAD 10",
				"sipush 248",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ILOAD 8",
				"ldc 2",
				"IADD",
				"ILOAD 9",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ALOAD 4",
				"ILOAD 8",
				"BALOAD",
				"sipush 192",
				"IAND",
				"sipush 128",
				"IF_ICMPNE",
				"GOTO",
				"NOP",
				"ALOAD 4",
				"ILOAD 8",
				"ldc 1",
				"IADD",
				"BALOAD",
				"sipush 192",
				"IAND",
				"sipush 128",
				"IF_ICMPNE",
				"GOTO",
				"NOP",
				"ALOAD 4",
				"ILOAD 8",
				"ldc 2",
				"IADD",
				"BALOAD",
				"sipush 192",
				"IAND",
				"sipush 128",
				"IF_ICMPNE",
				"GOTO",
				"NOP",
				"ILOAD 10",
				"bipush 7",
				"IAND",
				"bipush 18",
				"ISHL",
				"ALOAD 4",
				"ILOAD 8",
				"IINC 8",
				"BALOAD",
				"bipush 63",
				"IAND",
				"bipush 12",
				"ISHL",
				"IOR",
				"ALOAD 4",
				"ILOAD 8",
				"IINC 8",
				"BALOAD",
				"bipush 63",
				"IAND",
				"bipush 6",
				"ISHL",
				"IOR",
				"ALOAD 4",
				"ILOAD 8",
				"IINC 8",
				"BALOAD",
				"bipush 63",
				"IAND",
				"IOR",
				"ISTORE 11",
				"NOP",
				"ILOAD 11",
				"ldc 65536",
				"IF_ICMPLT",
				"GOTO",
				"NOP",
				"ILOAD 11",
				"ldc 1114111",
				"IF_ICMPLE",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ILOAD 8",
				"ldc 1",
				"IADD",
				"ILOAD 9",
				"IF_ICMPGE",
				"ALOAD 4",
				"ILOAD 8",
				"BALOAD",
				"sipush 192",
				"IAND",
				"sipush 128",
				"IF_ICMPNE",
				"GOTO",
				"NOP",
				"ALOAD 4",
				"ILOAD 8",
				"ldc 1",
				"IADD",
				"BALOAD",
				"sipush 192",
				"IAND",
				"sipush 128",
				"IF_ICMPNE",
				"GOTO",
				"NOP",
				"ILOAD 10",
				"bipush 15",
				"IAND",
				"bipush 12",
				"ISHL",
				"ALOAD 4",
				"ILOAD 8",
				"IINC 8",
				"BALOAD",
				"bipush 63",
				"IAND",
				"bipush 6",
				"ISHL",
				"IOR",
				"ALOAD 4",
				"ILOAD 8",
				"IINC 8",
				"BALOAD",
				"bipush 63",
				"IAND",
				"IOR",
				"ISTORE 11",
				"NOP",
				"ILOAD 11",
				"sipush 2048",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ILOAD 8",
				"ILOAD 9",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ALOAD 4",
				"ILOAD 8",
				"BALOAD",
				"sipush 192",
				"IAND",
				"sipush 128",
				"IF_ICMPNE",
				"GOTO",
				"NOP",
				"ILOAD 10",
				"bipush 31",
				"IAND",
				"bipush 6",
				"ISHL",
				"ALOAD 4",
				"ILOAD 8",
				"IINC 8",
				"BALOAD",
				"bipush 63",
				"IAND",
				"IOR",
				"ISTORE 11",
				"NOP",
				"ILOAD 11",
				"sipush 128",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ILOAD 10",
				"ldc 0",
				"IF_ICMPNE",
				"GOTO",
				"NOP",
				"ldc 65533",
				"ISTORE 11",
				"GOTO",
				"NOP",
				"ILOAD 10",
				"ISTORE 11",
				"NOP",
				"ALOAD 6",
				"ILOAD 7",
				"IINC 7",
				"ILOAD 11",
				"I2C",
				"CASTORE",
				"NOP",
				"GOTO"),
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"IFEQ",
				"GOTO",
				"NOP",
				"NEW",
				"DUP",
				"ldc ",
				"INVOKESPECIAL",
				"ATHROW",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 2",
				"NOP",
				"ILOAD 2",
				"ALOAD 0",
				"GETFIELD",
				"IADD",
				"ALOAD 0",
				"GETFIELD",
				"ARRAYLENGTH",
				"IF_ICMPLE",
				"GOTO",
				"NOP",
				"NEW",
				"DUP",
				"ldc ",
				"INVOKESPECIAL",
				"ATHROW",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 2",
				"INVOKESTATIC",
				"ASTORE 3",
				"NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ILOAD 2",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 3",
				"ARETURN")
		)
		),

		READ_BYTES("readBytes", List.of(
			List.of("NOP",
				"ILOAD 2",
				"ISTORE 4",
				"NOP",
				"ILOAD 4",
				"ILOAD 3",
				"ILOAD 2",
				"IADD",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ALOAD 1",
				"ILOAD 4",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"BASTORE",
				"IINC 4",
				"GOTO",
				"NOP",
				"RETURN"),
			List.of("NOP",
				"ILOAD 2",
				"ISTORE 4",
				"NOP",
				"ILOAD 4",
				"ILOAD 3",
				"ILOAD 2",
				"IADD",
				"IF_ICMPGE",
				"ALOAD 1",
				"ILOAD 4",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"BASTORE",
				"IINC 4",
				"GOTO",
				"NOP",
				"RETURN")
		)
		),

		READ_SHORT_SMART("readShortSmart", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"BALOAD",
				"sipush 255",
				"IAND",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"sipush 128",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"bipush 64",
				"ISUB",
				"IRETURN",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ldc 49152",
				"ISUB",
				"IRETURN"),
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"BALOAD",
				"sipush 255",
				"IAND",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"sipush 128",
				"IF_ICMPGE",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"bipush 64",
				"ISUB",
				"IRETURN",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ldc 49152",
				"ISUB",
				"IRETURN")
		)
		),

		READ_U_SHORT_SMART("readUShortSmart", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"BALOAD",
				"sipush 255",
				"IAND",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"sipush 128",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"IRETURN",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ldc 32768",
				"ISUB",
				"IRETURN")
		)
		),

		READ_SHORT_SMART_SUB("readShortSmartSub", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"BALOAD",
				"sipush 255",
				"IAND",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"sipush 128",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ldc 1",
				"ISUB",
				"IRETURN",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ldc 32769",
				"ISUB",
				"IRETURN")
		)
		),

		READ_INCR_SMALL_SMART("readIncrSmallSmart", List.of(
			List.of("NOP",
				"ldc 0",
				"ISTORE 1",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 2",
				"NOP",
				"ILOAD 2",
				"sipush 32767",
				"IF_ICMPNE",
				"GOTO",
				"NOP",
				"ILOAD 1",
				"ILOAD 2",
				"IADD",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"IRETURN",
				"NOP",
				"IINC 1",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 2",
				"GOTO")
		)
		),

		READ_LARGE_SMART("readLargeSmart", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"BALOAD",
				"IFGE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ldc 2147483647",
				"IAND",
				"IRETURN",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"IRETURN")
		)
		),

		READ_NULLABLE_LARGE_SMART("readNullableLargeSmart", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"BALOAD",
				"IFGE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ldc 2147483647",
				"IAND",
				"IRETURN",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"sipush 32767",
				"IF_ICMPNE",
				"ldc -1",
				"IRETURN",
				"NOP",
				"ILOAD 1",
				"IRETURN"),
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"BALOAD",
				"IFGE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ldc 2147483647",
				"IAND",
				"IRETURN",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"sipush 32767",
				"IF_ICMPNE",
				"GOTO",
				"NOP",
				"ldc -1",
				"IRETURN",
				"NOP",
				"ILOAD 1",
				"IRETURN")
		)
		),

		READ_VAR_INT("readVarInt", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"ISTORE 1",
				"NOP",
				"ldc 0",
				"ISTORE 2",
				"NOP",
				"ILOAD 1",
				"IFGE",
				"GOTO",
				"NOP",
				"ILOAD 2",
				"ILOAD 1",
				"IOR",
				"IRETURN",
				"NOP",
				"ILOAD 2",
				"ILOAD 1",
				"bipush 127",
				"IAND",
				"IOR",
				"bipush 7",
				"ISHL",
				"ISTORE 2",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"ISTORE 1",
				"GOTO")
		)
		),

		PACK_BYTES_TO_INT("packBytesToInt", List.of(
			List.of("NOP",
				"ldc 0",
				"ISTORE 2",
				"NOP",
				"ldc 0",
				"ISTORE 3",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 1",
				"NOP",
				"ILOAD 2",
				"ILOAD 1",
				"bipush 127",
				"IAND",
				"ILOAD 3",
				"ISHL",
				"IOR",
				"ISTORE 2",
				"NOP",
				"IINC 3",
				"NOP",
				"ILOAD 1",
				"bipush 127",
				"IF_ICMPGT",
				"GOTO",
				"NOP",
				"ILOAD 2",
				"IRETURN")
		)
		),

		XTEA_ENCRYPT_ALL("xteaEncryptAll", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"bipush 8",
				"IDIV",
				"ISTORE 2",
				"NOP",
				"ALOAD 0",
				"ldc 0",
				"PUTFIELD",
				"NOP",
				"ldc 0",
				"ISTORE 3",
				"NOP",
				"ILOAD 3",
				"ILOAD 2",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"RETURN",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 4",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 5",
				"NOP",
				"ldc 0",
				"ISTORE 6",
				"NOP",
				"ldc -1640531527",
				"ISTORE 7",
				"NOP",
				"bipush 32",
				"ISTORE 8",
				"NOP",
				"ILOAD 8",
				"IINC 8",
				"IFLE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 8",
				"ISUB",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"ILOAD 4",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 5",
				"INVOKEVIRTUAL",
				"NOP",
				"IINC 3",
				"GOTO",
				"NOP",
				"ILOAD 5",
				"ILOAD 5",
				"ldc 4",
				"ISHL",
				"ILOAD 5",
				"ldc 5",
				"IUSHR",
				"IXOR",
				"IADD",
				"ILOAD 6",
				"ALOAD 1",
				"ILOAD 6",
				"ldc 3",
				"IAND",
				"IALOAD",
				"IADD",
				"IXOR",
				"ILOAD 4",
				"IADD",
				"ISTORE 4",
				"NOP",
				"ILOAD 6",
				"ILOAD 7",
				"IADD",
				"ISTORE 6",
				"NOP",
				"ILOAD 4",
				"ILOAD 4",
				"ldc 4",
				"ISHL",
				"ILOAD 4",
				"ldc 5",
				"IUSHR",
				"IXOR",
				"IADD",
				"ALOAD 1",
				"ILOAD 6",
				"bipush 11",
				"IUSHR",
				"ldc 3",
				"IAND",
				"IALOAD",
				"ILOAD 6",
				"IADD",
				"IXOR",
				"ILOAD 5",
				"IADD",
				"ISTORE 5",
				"GOTO"),
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"bipush 8",
				"IDIV",
				"ISTORE 2",
				"NOP",
				"ALOAD 0",
				"ldc 0",
				"PUTFIELD",
				"NOP",
				"ldc 0",
				"ISTORE 3",
				"NOP",
				"ILOAD 3",
				"ILOAD 2",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"RETURN",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 4",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 5",
				"NOP",
				"ldc 0",
				"ISTORE 6",
				"NOP",
				"ldc -1640531527",
				"ISTORE 7",
				"NOP",
				"bipush 32",
				"ISTORE 8",
				"NOP",
				"ILOAD 8",
				"IINC 8",
				"IFLE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 8",
				"ISUB",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"ILOAD 4",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 5",
				"INVOKEVIRTUAL",
				"NOP",
				"IINC 3",
				"GOTO",
				"NOP",
				"ILOAD 5",
				"ILOAD 5",
				"ldc 4",
				"ISHL",
				"ILOAD 5",
				"ldc 5",
				"IUSHR",
				"IXOR",
				"IADD",
				"ILOAD 6",
				"ALOAD 1",
				"ILOAD 6",
				"ldc 3",
				"IAND",
				"IALOAD",
				"IADD",
				"IXOR",
				"ILOAD 4",
				"IADD",
				"ISTORE 4",
				"NOP",
				"ILOAD 6",
				"ILOAD 7",
				"IADD",
				"ISTORE 6",
				"NOP",
				"ILOAD 5",
				"ILOAD 4",
				"ILOAD 4",
				"ldc 4",
				"ISHL",
				"ILOAD 4",
				"ldc 5",
				"IUSHR",
				"IXOR",
				"IADD",
				"ALOAD 1",
				"ILOAD 6",
				"bipush 11",
				"IUSHR",
				"ldc 3",
				"IAND",
				"IALOAD",
				"ILOAD 6",
				"IADD",
				"IXOR",
				"IADD",
				"ISTORE 5",
				"GOTO"),
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"bipush 8",
				"IDIV",
				"ISTORE 2",
				"NOP",
				"ALOAD 0",
				"ldc 0",
				"PUTFIELD",
				"NOP",
				"ldc 0",
				"ISTORE 3",
				"NOP",
				"ILOAD 3",
				"ILOAD 2",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"RETURN",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 4",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 5",
				"NOP",
				"ldc 0",
				"ISTORE 6",
				"NOP",
				"ldc -1640531527",
				"ISTORE 7",
				"NOP",
				"bipush 32",
				"ISTORE 8",
				"NOP",
				"ILOAD 8",
				"IINC 8",
				"IFLE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 8",
				"ISUB",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"ILOAD 4",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 5",
				"INVOKEVIRTUAL",
				"NOP",
				"IINC 3",
				"GOTO",
				"NOP",
				"ILOAD 4",
				"ILOAD 5",
				"ILOAD 5",
				"ldc 4",
				"ISHL",
				"ILOAD 5",
				"ldc 5",
				"IUSHR",
				"IXOR",
				"IADD",
				"ILOAD 6",
				"ALOAD 1",
				"ILOAD 6",
				"ldc 3",
				"IAND",
				"IALOAD",
				"IADD",
				"IXOR",
				"IADD",
				"ISTORE 4",
				"NOP",
				"ILOAD 6",
				"ILOAD 7",
				"IADD",
				"ISTORE 6",
				"NOP",
				"ILOAD 5",
				"ILOAD 4",
				"ILOAD 4",
				"ldc 4",
				"ISHL",
				"ILOAD 4",
				"ldc 5",
				"IUSHR",
				"IXOR",
				"IADD",
				"ALOAD 1",
				"ILOAD 6",
				"bipush 11",
				"IUSHR",
				"ldc 3",
				"IAND",
				"IALOAD",
				"ILOAD 6",
				"IADD",
				"IXOR",
				"IADD",
				"ISTORE 5",
				"GOTO")
		)
		),

		XTEA_DECRYPT_ALL("xteaDecryptAll", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"bipush 8",
				"IDIV",
				"ISTORE 2",
				"NOP",
				"ALOAD 0",
				"ldc 0",
				"PUTFIELD",
				"NOP",
				"ldc 0",
				"ISTORE 3",
				"NOP",
				"ILOAD 3",
				"ILOAD 2",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"RETURN",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 4",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 5",
				"NOP",
				"ldc -957401312",
				"ISTORE 6",
				"NOP",
				"ldc -1640531527",
				"ISTORE 7",
				"NOP",
				"bipush 32",
				"ISTORE 8",
				"NOP",
				"ILOAD 8",
				"IINC 8",
				"IFLE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 8",
				"ISUB",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"ILOAD 4",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 5",
				"INVOKEVIRTUAL",
				"NOP",
				"IINC 3",
				"GOTO",
				"NOP",
				"ILOAD 5",
				"ILOAD 4",
				"ILOAD 4",
				"ldc 4",
				"ISHL",
				"ILOAD 4",
				"ldc 5",
				"IUSHR",
				"IXOR",
				"IADD",
				"ALOAD 1",
				"ILOAD 6",
				"bipush 11",
				"IUSHR",
				"ldc 3",
				"IAND",
				"IALOAD",
				"ILOAD 6",
				"IADD",
				"IXOR",
				"ISUB",
				"ISTORE 5",
				"NOP",
				"ILOAD 6",
				"ILOAD 7",
				"ISUB",
				"ISTORE 6",
				"NOP",
				"ILOAD 4",
				"ILOAD 5",
				"ILOAD 5",
				"ldc 4",
				"ISHL",
				"ILOAD 5",
				"ldc 5",
				"IUSHR",
				"IXOR",
				"IADD",
				"ILOAD 6",
				"ALOAD 1",
				"ILOAD 6",
				"ldc 3",
				"IAND",
				"IALOAD",
				"IADD",
				"IXOR",
				"ISUB",
				"ISTORE 4",
				"GOTO")
		)
		),

		XTEA_ENCRYPT("xteaEncrypt", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ISTORE 4",
				"NOP",
				"ALOAD 0",
				"ILOAD 2",
				"PUTFIELD",
				"NOP",
				"ILOAD 3",
				"ILOAD 2",
				"ISUB",
				"bipush 8",
				"IDIV",
				"ISTORE 5",
				"NOP",
				"ldc 0",
				"ISTORE 6",
				"NOP",
				"ILOAD 6",
				"ILOAD 5",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"ILOAD 4",
				"PUTFIELD",
				"NOP",
				"RETURN",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 7",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 8",
				"NOP",
				"ldc 0",
				"ISTORE 9",
				"NOP",
				"ldc -1640531527",
				"ISTORE 10",
				"NOP",
				"bipush 32",
				"ISTORE 11",
				"NOP",
				"ILOAD 11",
				"IINC 11",
				"IFLE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 8",
				"ISUB",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"ILOAD 7",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 8",
				"INVOKEVIRTUAL",
				"NOP",
				"IINC 6",
				"GOTO",
				"NOP",
				"ILOAD 7",
				"ILOAD 8",
				"ILOAD 8",
				"ldc 4",
				"ISHL",
				"ILOAD 8",
				"ldc 5",
				"IUSHR",
				"IXOR",
				"IADD",
				"ILOAD 9",
				"ALOAD 1",
				"ILOAD 9",
				"ldc 3",
				"IAND",
				"IALOAD",
				"IADD",
				"IXOR",
				"IADD",
				"ISTORE 7",
				"NOP",
				"ILOAD 9",
				"ILOAD 10",
				"IADD",
				"ISTORE 9",
				"NOP",
				"ILOAD 7",
				"ILOAD 7",
				"ldc 4",
				"ISHL",
				"ILOAD 7",
				"ldc 5",
				"IUSHR",
				"IXOR",
				"IADD",
				"ALOAD 1",
				"ILOAD 9",
				"bipush 11",
				"IUSHR",
				"ldc 3",
				"IAND",
				"IALOAD",
				"ILOAD 9",
				"IADD",
				"IXOR",
				"ILOAD 8",
				"IADD",
				"ISTORE 8",
				"GOTO"),
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ISTORE 4",
				"NOP",
				"ALOAD 0",
				"ILOAD 2",
				"PUTFIELD",
				"NOP",
				"ILOAD 3",
				"ILOAD 2",
				"ISUB",
				"bipush 8",
				"IDIV",
				"ISTORE 5",
				"NOP",
				"ldc 0",
				"ISTORE 6",
				"NOP",
				"ILOAD 6",
				"ILOAD 5",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"ILOAD 4",
				"PUTFIELD",
				"NOP",
				"RETURN",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 7",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 8",
				"NOP",
				"ldc 0",
				"ISTORE 9",
				"NOP",
				"ldc -1640531527",
				"ISTORE 10",
				"NOP",
				"bipush 32",
				"ISTORE 11",
				"NOP",
				"ILOAD 11",
				"IINC 11",
				"IFLE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 8",
				"ISUB",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"ILOAD 7",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 8",
				"INVOKEVIRTUAL",
				"NOP",
				"IINC 6",
				"GOTO",
				"NOP",
				"ILOAD 7",
				"ILOAD 8",
				"ILOAD 8",
				"ldc 4",
				"ISHL",
				"ILOAD 8",
				"ldc 5",
				"IUSHR",
				"IXOR",
				"IADD",
				"ILOAD 9",
				"ALOAD 1",
				"ILOAD 9",
				"ldc 3",
				"IAND",
				"IALOAD",
				"IADD",
				"IXOR",
				"IADD",
				"ISTORE 7",
				"NOP",
				"ILOAD 9",
				"ILOAD 10",
				"IADD",
				"ISTORE 9",
				"NOP",
				"ILOAD 8",
				"ILOAD 7",
				"ILOAD 7",
				"ldc 4",
				"ISHL",
				"ILOAD 7",
				"ldc 5",
				"IUSHR",
				"IXOR",
				"IADD",
				"ALOAD 1",
				"ILOAD 9",
				"bipush 11",
				"IUSHR",
				"ldc 3",
				"IAND",
				"IALOAD",
				"ILOAD 9",
				"IADD",
				"IXOR",
				"IADD",
				"ISTORE 8",
				"GOTO")
		)
		),

		XTEA_DECRYPT("xteaDecrypt", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ISTORE 4",
				"NOP",
				"ALOAD 0",
				"ILOAD 2",
				"PUTFIELD",
				"NOP",
				"ILOAD 3",
				"ILOAD 2",
				"ISUB",
				"bipush 8",
				"IDIV",
				"ISTORE 5",
				"NOP",
				"ldc 0",
				"ISTORE 6",
				"NOP",
				"ILOAD 6",
				"ILOAD 5",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"ILOAD 4",
				"PUTFIELD",
				"NOP",
				"RETURN",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 7",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 8",
				"NOP",
				"ldc -957401312",
				"ISTORE 9",
				"NOP",
				"ldc -1640531527",
				"ISTORE 10",
				"NOP",
				"bipush 32",
				"ISTORE 11",
				"NOP",
				"ILOAD 11",
				"IINC 11",
				"IFLE",
				"GOTO",
				"NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 8",
				"ISUB",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"ILOAD 7",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ILOAD 8",
				"INVOKEVIRTUAL",
				"NOP",
				"IINC 6",
				"GOTO",
				"NOP",
				"ILOAD 8",
				"ILOAD 7",
				"ILOAD 7",
				"ldc 4",
				"ISHL",
				"ILOAD 7",
				"ldc 5",
				"IUSHR",
				"IXOR",
				"IADD",
				"ALOAD 1",
				"ILOAD 9",
				"bipush 11",
				"IUSHR",
				"ldc 3",
				"IAND",
				"IALOAD",
				"ILOAD 9",
				"IADD",
				"IXOR",
				"ISUB",
				"ISTORE 8",
				"NOP",
				"ILOAD 9",
				"ILOAD 10",
				"ISUB",
				"ISTORE 9",
				"NOP",
				"ILOAD 7",
				"ILOAD 8",
				"ILOAD 8",
				"ldc 4",
				"ISHL",
				"ILOAD 8",
				"ldc 5",
				"IUSHR",
				"IXOR",
				"IADD",
				"ILOAD 9",
				"ALOAD 1",
				"ILOAD 9",
				"ldc 3",
				"IAND",
				"IALOAD",
				"IADD",
				"IXOR",
				"ISUB",
				"ISTORE 7",
				"GOTO")
		)
		),

		ENCRYPT_RSA("encryptRsa", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ISTORE 3",
				"NOP",
				"ALOAD 0",
				"ldc 0",
				"PUTFIELD",
				"NOP",
				"ILOAD 3",
				"NEWARRAY",
				"ASTORE 4",
				"NOP",
				"ALOAD 0",
				"ALOAD 4",
				"ldc 0",
				"ILOAD 3",
				"INVOKEVIRTUAL",
				"NOP",
				"NEW",
				"DUP",
				"ALOAD 4",
				"INVOKESPECIAL",
				"ASTORE 5",
				"NOP",
				"ALOAD 5",
				"ALOAD 1",
				"ALOAD 2",
				"INVOKEVIRTUAL",
				"ASTORE 6",
				"NOP",
				"ALOAD 6",
				"INVOKEVIRTUAL",
				"ASTORE 7",
				"NOP",
				"ALOAD 0",
				"ldc 0",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"ALOAD 7",
				"ARRAYLENGTH",
				"INVOKEVIRTUAL",
				"NOP",
				"ALOAD 0",
				"ALOAD 7",
				"ldc 0",
				"ALOAD 7",
				"ARRAYLENGTH",
				"INVOKEVIRTUAL",
				"NOP",
				"RETURN")
		)
		),

		WRITE_CRC("writeCrc", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ILOAD 1",
				"ALOAD 0",
				"GETFIELD",
				"INVOKESTATIC",
				"ISTORE 2",
				"NOP",
				"ALOAD 0",
				"ILOAD 2",
				"INVOKEVIRTUAL",
				"NOP",
				"ILOAD 2",
				"IRETURN"),
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ASTORE 3",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ISTORE 4",
				"NOP",
				"ldc -1",
				"ISTORE 5",
				"NOP",
				"ILOAD 1",
				"ISTORE 6",
				"NOP",
				"ILOAD 6",
				"ILOAD 4",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ILOAD 5",
				"ldc -1",
				"IXOR",
				"ISTORE 5",
				"NOP",
				"ILOAD 5",
				"ISTORE 2",
				"NOP",
				"ILOAD 2",
				"ISTORE 5",
				"NOP",
				"ALOAD 0",
				"ILOAD 5",
				"INVOKEVIRTUAL",
				"NOP",
				"ILOAD 5",
				"IRETURN",
				"NOP",
				"ILOAD 5",
				"bipush 8",
				"IUSHR",
				"GETSTATIC",
				"ILOAD 5",
				"ALOAD 3",
				"ILOAD 6",
				"BALOAD",
				"IXOR",
				"sipush 255",
				"IAND",
				"IALOAD",
				"IXOR",
				"ISTORE 5",
				"NOP",
				"IINC 6",
				"GOTO")
		)
		),

		CHECK_CRC("checkCrc", List.of(
			List.of("NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 4",
				"ISUB",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ldc 0",
				"ALOAD 0",
				"GETFIELD",
				"INVOKESTATIC",
				"ISTORE 1",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 2",
				"NOP",
				"ILOAD 1",
				"ILOAD 2",
				"IF_ICMPNE",
				"ldc 1",
				"IRETURN",
				"NOP",
				"ldc 0",
				"IRETURN"),
			List.of("NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 4",
				"ISUB",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ldc 0",
				"ALOAD 0",
				"GETFIELD",
				"INVOKESTATIC",
				"ISTORE 1",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 2",
				"NOP",
				"ILOAD 2",
				"ILOAD 1",
				"IF_ICMPNE",
				"GOTO",
				"NOP",
				"ldc 1",
				"IRETURN",
				"NOP",
				"ldc 0",
				"IRETURN"),
			List.of("NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 4",
				"ISUB",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ASTORE 2",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ISTORE 3",
				"NOP",
				"ldc -1",
				"ISTORE 4",
				"NOP",
				"ldc 0",
				"ISTORE 5",
				"NOP",
				"ILOAD 5",
				"ILOAD 3",
				"IF_ICMPGE",
				"GOTO",
				"NOP",
				"ILOAD 4",
				"ldc -1",
				"IXOR",
				"ISTORE 4",
				"NOP",
				"ILOAD 4",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"ISTORE 4",
				"NOP",
				"ALOAD 0",
				"INVOKEVIRTUAL",
				"ISTORE 5",
				"NOP",
				"ILOAD 5",
				"ILOAD 4",
				"IF_ICMPNE",
				"ldc 1",
				"IRETURN",
				"NOP",
				"ldc 0",
				"IRETURN",
				"NOP",
				"ILOAD 4",
				"bipush 8",
				"IUSHR",
				"GETSTATIC",
				"ILOAD 4",
				"ALOAD 2",
				"ILOAD 5",
				"BALOAD",
				"IXOR",
				"sipush 255",
				"IAND",
				"IALOAD",
				"IXOR",
				"ISTORE 4",
				"NOP",
				"IINC 5",
				"GOTO")
		)
		),

		WRITE_BYTE_ADD("writeByteAdd", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"sipush 128",
				"IADD",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN")
		)
		),

		WRITE_BYTE_NEG("writeByteNeg", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ldc 0",
				"ILOAD 1",
				"ISUB",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN")
		)
		),

		WRITE_BYTE_SUB("writeByteSub", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"sipush 128",
				"ILOAD 1",
				"ISUB",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN")
		)
		),

		READ_UNSIGNED_BYTE_ADD("readUnsignedByteAdd", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"sipush 128",
				"ISUB",
				"sipush 255",
				"IAND",
				"IRETURN")
		)
		),

		READ_UNSIGNED_BYTE_NEG("readUnsignedByteNeg", List.of(
			List.of("NOP",
				"ldc 0",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"ISUB",
				"sipush 255",
				"IAND",
				"IRETURN")
		)
		),

		READ_UNSIGNED_BYTE_SUB("readUnsignedByteSub", List.of(
			List.of("NOP",
				"sipush 128",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"ISUB",
				"sipush 255",
				"IAND",
				"IRETURN")
		)
		),

		READ_BYTE_ADD("readByteAdd", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"sipush 128",
				"ISUB",
				"I2B",
				"IRETURN")
		)
		),

		READ_BYTE_NEG("readByteNeg", List.of(
			List.of("NOP",
				"ldc 0",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"ISUB",
				"I2B",
				"IRETURN")
		)
		),

		READ_BYTE_SUB("readByteSub", List.of(
			List.of("NOP",
				"sipush 128",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"ISUB",
				"I2B",
				"IRETURN")
		)
		),

		WRITE_SHORT_LE("writeShortLE", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"bipush 8",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN")
		)
		),

		WRITE_SHORT_ADD_LE("writeShortAddLE", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"bipush 8",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"sipush 128",
				"IADD",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN")
		)
		),

		WRITE_SHORT_ADD("writeShortAdd", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"sipush 128",
				"IADD",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"bipush 8",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN")
		)
		),

		READ_UNSIGNED_SHORT_LE("readUnsignedShortLE", List.of(
			List.of("NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 2",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 8",
				"ISHL",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 2",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"IADD",
				"IRETURN")
		)
		),

		READ_UNSIGNED_SHORT_ADD("readUnsignedShortAdd", List.of(
			List.of("NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 2",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"sipush 128",
				"ISUB",
				"sipush 255",
				"IAND",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 2",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 8",
				"ISHL",
				"IADD",
				"IRETURN")
		)
		),

		READ_UNSIGNED_SHORT_ADD_LE("readUnsignedShortAddLE", List.of(
			List.of("NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 2",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 8",
				"ISHL",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 2",
				"ISUB",
				"BALOAD",
				"sipush 128",
				"ISUB",
				"sipush 255",
				"IAND",
				"IADD",
				"IRETURN")
		)
		),

		READ_SHORT_LE("readShortLE", List.of(
			List.of("NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 2",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"sipush 128",
				"ISUB",
				"sipush 255",
				"IAND",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 2",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 8",
				"ISHL",
				"IADD",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"sipush 32767",
				"IF_ICMPLE",
				"GOTO",
				"NOP",
				"ILOAD 1",
				"ldc 65536",
				"ISUB",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"IRETURN"),
			List.of("NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 2",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 8",
				"ISHL",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 2",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"IADD",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"sipush 32767",
				"IF_ICMPLE",
				"GOTO",
				"NOP",
				"ILOAD 1",
				"ldc 65536",
				"ISUB",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"IRETURN")
		)
		),

		READ_SIGNED_SHORT("readSignedShort", List.of(
			List.of("NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 2",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 8",
				"ISHL",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 2",
				"ISUB",
				"BALOAD",
				"sipush 128",
				"ISUB",
				"sipush 255",
				"IAND",
				"IADD",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"sipush 32767",
				"IF_ICMPLE",
				"GOTO",
				"NOP",
				"ILOAD 1",
				"ldc 65536",
				"ISUB",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"IRETURN"),
			List.of("NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 2",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 8",
				"ISHL",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 2",
				"ISUB",
				"BALOAD",
				"sipush 128",
				"ISUB",
				"sipush 255",
				"IAND",
				"IADD",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"sipush 32767",
				"IF_ICMPLE",
				"ILOAD 1",
				"ldc 65536",
				"ISUB",
				"ISTORE 1",
				"NOP",
				"ILOAD 1",
				"IRETURN")
		)
		),

		WRITE_INT_LE("writeIntLE", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"bipush 8",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"bipush 16",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"bipush 24",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN")
		)
		),

		WRITE_INT_ME("writeIntME", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"bipush 8",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"bipush 24",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"bipush 16",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN")
		)
		),

		WRITE_INT_IME("writeIntIME", List.of(
			List.of("NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"bipush 16",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"bipush 24",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"I2B",
				"BASTORE",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 1",
				"IADD",
				"DUP_X1",
				"PUTFIELD",
				"ldc 1",
				"ISUB",
				"ILOAD 1",
				"bipush 8",
				"ISHR",
				"I2B",
				"BASTORE",
				"NOP",
				"RETURN")
		)
		),

		READ_UNSIGNED_INT_LE("readUnsignedIntLE", List.of(
			List.of("NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 4",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 4",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 3",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 8",
				"ISHL",
				"IADD",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 2",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 16",
				"ISHL",
				"IADD",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 24",
				"ISHL",
				"IADD",
				"IRETURN")
		)
		),

		READ_UNSIGNED_INT_IME("readUnsignedIntIME", List.of(
			List.of("NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 4",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 2",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 24",
				"ISHL",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 4",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 8",
				"ISHL",
				"IADD",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 3",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"IADD",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 16",
				"ISHL",
				"IADD",
				"IRETURN")
		)
		),

		READ_UNSIGNED_INT_ME("readUnsignedIntME", List.of(
			List.of("NOP",
				"ALOAD 0",
				"DUP",
				"GETFIELD",
				"ldc 4",
				"IADD",
				"PUTFIELD",
				"NOP",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 1",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 8",
				"ISHL",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 4",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 16",
				"ISHL",
				"IADD",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 2",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"IADD",
				"ALOAD 0",
				"GETFIELD",
				"ALOAD 0",
				"GETFIELD",
				"ldc 3",
				"ISUB",
				"BALOAD",
				"sipush 255",
				"IAND",
				"bipush 24",
				"ISHL",
				"IADD",
				"IRETURN")
		)
		),
		;

		public static final Map<String, TargetBufferMethods> TARGET_BUFFER_METHODS = new HashMap<>();

		static
		{
			for (final TargetBufferMethods targetBufferMethod : TargetBufferMethods.values())
			{
				TARGET_BUFFER_METHODS.put(targetBufferMethod.name, targetBufferMethod);
			}
		}

		private final String name;
		private final List<List<String>> instructions;
	}
}