import net.runelite.mapping.Export;
import net.runelite.mapping.ObfuscatedName;
import net.runelite.mapping.ObfuscatedSignature;

@ObfuscatedName("or")
public class class387 {
	@ObfuscatedName("gw")
	@ObfuscatedSignature(
		descriptor = "Lrr;"
	)
	static GraphicsDefaults field4432;

	@ObfuscatedName("ha")
	@ObfuscatedSignature(
		descriptor = "(IB)V",
		garbageValue = "0"
	)
	@Export("getLoginError")
	static void getLoginError(int var0) {
		int var1 = class466.method8377();
		if (var0 == -3) {
			class318.setLoginResponseString("Connection timed out.", "Please try using a different world.", "");
		} else if (var0 == -2) {
			class318.setLoginResponseString("Error connecting to server.", "Please try using a different world.", "");
		} else if (var0 == -1) {
			class318.setLoginResponseString("No response from server.", "Please try using a different world.", "");
		} else if (var0 == 3) {
			PcmPlayer.method838(3);
			Login.field943 = 1;
		} else if (var0 == 4) {
			PcmPlayer.method838(14);
			Login.Login_banType = 0;
		} else if (var0 == 5) {
			Login.field943 = 2;
			class318.setLoginResponseString("Either your account is still logged in, or the last", "world you were using has become unavailable.", "Please try again later.");
		} else if (var0 == 68) {
			if (!Client.field537) {
				Client.field537 = true;
				class415.method7708();
				return;
			}

			class318.setLoginResponseString("RuneScape has been updated!", "Please reload this page.", "");
		} else if (!Client.onMobile && var0 == 6) {
			class318.setLoginResponseString("RuneScape has been updated!", "Please reload this page.", "");
		} else if (var0 == 7) {
			class318.setLoginResponseString("This world is full.", "Please use a different world.", "");
		} else if (var0 == 8) {
			class318.setLoginResponseString("Unable to connect.", "Login server offline.", "");
		} else if (var0 == 9) {
			class318.setLoginResponseString("Login limit exceeded.", "Too many connections from your address.", "");
		} else if (var0 == 10) {
			class318.setLoginResponseString("Unable to connect.", "Bad session id.", "");
		} else if (var0 == 11) {
			class318.setLoginResponseString("We suspect someone knows your password.", "Press 'change your password' on front page.", "");
		} else if (var0 == 12) {
			class318.setLoginResponseString("You need a members account to login to this world.", "Please subscribe, or use a different world.", "");
		} else if (var0 == 13) {
			class318.setLoginResponseString("Could not complete login.", "Please try using a different world.", "");
		} else if (var0 == 14) {
			class318.setLoginResponseString("The server is being updated.", "Please wait 1 minute and try again.", "");
		} else if (var0 == 16) {
			class318.setLoginResponseString("Too many login attempts.", "You can use the Jagex Launcher to continue playing.", "Press the button below to download it now.");
			PcmPlayer.method838(33);
		} else if (var0 == 17) {
			class318.setLoginResponseString("To access this free world, log into a", "members world and move your character", "to a non-members area.");
		} else if (var0 == 18) {
			PcmPlayer.method838(14);
			Login.Login_banType = 1;
		} else if (var0 == 19) {
			class318.setLoginResponseString("This world is running a closed Beta.", "Sorry invited players only.", "Please use a different world.");
		} else if (var0 == 20) {
			class318.setLoginResponseString("Invalid loginserver requested.", "Please try using a different world.", "");
		} else if (var0 == 22) {
			class318.setLoginResponseString("Malformed login packet.", "Please try again.", "");
		} else if (var0 == 23) {
			class318.setLoginResponseString("No reply from loginserver.", "Please wait 1 minute and try again.", "");
		} else if (var0 == 24) {
			class318.setLoginResponseString("Error loading your profile.", "Please contact customer support.", "");
		} else if (var0 == 25) {
			class318.setLoginResponseString("Unexpected loginserver response.", "Please try using a different world.", "");
		} else if (var0 == 26) {
			class318.setLoginResponseString("This computers address has been blocked", "as it was used to break our rules.", "");
		} else if (var0 == 27) {
			class318.setLoginResponseString("", "Service unavailable.", "");
		} else if (var0 == 31) {
			class318.setLoginResponseString("Your account must have a displayname set", "in order to play the game.  Please set it", "via the website, or the main game.");
		} else if (var0 == 32) {
			PcmPlayer.method838(14);
			Login.Login_banType = 2;
		} else if (var0 == 37) {
			class318.setLoginResponseString("Your account is currently inaccessible.", "Please try again in a few minutes.", "");
		} else if (var0 == 38) {
			class318.setLoginResponseString("You need to vote to play!", "Visit runescape.com and vote,", "and then come back here!");
		} else if (var0 == 55) {
			PcmPlayer.method838(8);
		} else {
			if (var0 == 56) {
				class318.setLoginResponseString("Enter the 6-digit code generated by your", "authenticator app.", "");
				MusicSong.updateGameState(11);
				return;
			}

			if (var0 == 57) {
				class318.setLoginResponseString("The code you entered was incorrect.", "Please try again.", "");
				MusicSong.updateGameState(11);
				return;
			}

			if (var0 == 61) {
				class318.setLoginResponseString("", "Please enter your date of birth (DD/MM/YYYY)", "");
				PcmPlayer.method838(7);
			} else {
				if (var0 == 62) {
					MusicSong.updateGameState(10);
					PcmPlayer.method838(9);
					class318.setLoginResponseString("Login attempt timed out.", "Please try again.", "");
					return;
				}

				if (var0 == 63) {
					MusicSong.updateGameState(10);
					PcmPlayer.method838(9);
					class318.setLoginResponseString("You were signed out.", "Please sign in again.", "");
					return;
				}

				if (var0 == 65 || var0 == 67) {
					MusicSong.updateGameState(10);
					PcmPlayer.method838(9);
					class318.setLoginResponseString("Failed to login.", "Please try again.", "");
					return;
				}

				if (var0 == 71) {
					MusicSong.updateGameState(10);
					PcmPlayer.method838(7);
					class318.setLoginResponseString("There was a problem updating your DOB.", "Please try again later. If the problem ", "persists, please contact Jagex Support.");
				} else if (var0 == 73) {
					MusicSong.updateGameState(10);
					PcmPlayer.method838(6);
					class318.setLoginResponseString("Your date of birth information is waiting", "to be reviewed by our staff.", "It will be processed shortly.");
				} else if (var0 == 72) {
					MusicSong.updateGameState(10);
					PcmPlayer.method838(32);
				} else {
					class318.setLoginResponseString("Unexpected server response", "Please try using a different world.", "");
				}
			}
		}

		MusicSong.updateGameState(10);
		boolean var2 = var1 != class466.method8377();
		if (!var2 && Client.field571.method9339()) {
			PcmPlayer.method838(9);
		}

	}
}
