[achievement_diary]
id=259
container=2

[achievement_diary_scroll]
id=741
title=2
text=3

[adventure_log]
id=187
container=0

[agility_arena]
id=5
light_indicator=2

[ba_attacker]
id=485
role_sprite=11
role=12

[ba_collector]
id=486
role_sprite=10
role=11

[ba_defender]
id=487
role_sprite=10
role=11

[ba_healer]
id=488
role_sprite=10
role=11
teammates=13
teammate1=18
teammate2=22
teammate3=26
teammate4=30

[ba_reward]
id=497
reward_text=57

[ba_team]
id=256
team=2

[bank]
id=12
container=1
title_bar=3
tutorial_button=4
item_count_top=5
item_count_bar=6
item_count_bottom=7
group_storage_button=8
content_container=10
tab_container=11
item_container=13
scrollbar=14
search_button_background=40
deposit_inventory=42
deposit_equipment=44
incinerator=46
incinerator_confirm=47
equipment_content_container=69
settings_button=113
equipment_button=114
popup=116

[bank_inventory]
id=15
item_container=3
equipment_item_container=4

[bank_pin]
id=213
container=0

[barrows]
id=24
brothers=4
potential=5

[barrows_puzzle]
id=25
parent=0
sequence_1=3
answer1_container=12
answer1=13
answer2_container=14
answer2=15
answer3_container=16
answer3=17

[barrows_reward]
id=155

[bgr_rank_draughts]
id=34
display=2

[bgr_rank_runelink]
id=38
display=2

[bgr_rank_runesquares]
id=42
display=2

[bgr_rank_runeversi]
id=46
display=2

[blast_furnace]
id=474
coffer=2

[blast_mine]
id=598
container=2

[chambers_of_xeric_storage_unit_private]
id=271
item_container=6

[chambers_of_xeric_storage_unit_shared]
id=550

[chambers_of_xeric_inventory]
id=551

[chambers_of_xeric_reward]
id=539

[character_summary]
id=712
container=2

[chatbox]
id=162
parent=0
buttons=1
tab_all=4
tab_game=7
tab_public=11
tab_private=15
tab_channel=19
tab_clan=23
tab_trade=27
report_text=33
frame=34
transparent_background=35
container=37
title=41
full_input=42
ge_search_results=50
messages=53
transparent_background_lines=54
input=55
message_lines=56
first_message=57

[clan]
id=701
layer=0
header=1
members=6

[clan_guest]
id=702
layer=0
header=1
members=6

[clanrank_popup]
id=289

[cluescroll]
id=203
text=2

[cluescroll_reward]
id=73
item_container=3

[clue_beginner_map_champions_guild]
id=346

[clue_beginner_map_dyanor]
id=348

[clue_beginner_map_north_of_falador]
id=351

[clue_beginner_map_varrock_east_mine]
id=347

[clue_beginner_map_wizards_tower]
id=356

[collection_log]
id=621
container=0
tabs=3
entry=17
entry_header=19
entry_items=36

[combat]
id=593
level=3
style_one=4
style_two=8
style_three=12
style_four=16
spells=20
defensive_spell_box=21
defensive_spell_icon=23
defensive_spell_shield=24
defensive_spell_text=25
spell_box=26
spell_icon=28
spell_text=29
auto_retaliate=30

[corp_damage]
id=13

[deposit_box]
id=192
inventory_item_container=2

[destroy_item]
id=584
yes=1
no=3
name=6

[dialog_double_sprite]
id=11
sprite1=1
text=2
sprite2=3

[dialog_npc]
id=231
head_model=2
name=4
text=6

[dialog_option]
id=219
options=1

[dialog_player]
id=217
text=6

[dialog_sprite]
id=193
sprite=1
text=2

[diary]
id=119
title=2
text=3

[drift_net_fishing_reward]
id=607

[duel_inventory]
id=421

[duel_inventory_other]
id=481

[emotes]
id=216
window=0
emote_scroll_container=1
emote_container=2
emote_scrollbar=4

[equipment]
id=387
inventory_item_container=0

[equipment_inventory]
id=85

[experience_tracker]
id=122
widget=4
bottom_bar=16

[explorers_ring]
id=483
inventory=7

[fairy_ring]
id=398
teleport_button=26

[fairy_ring_panel]
id=381
header=2
list=7
favorites=8
separator=9
scrollbar=152

[fixed_viewport]
id=548
minimap=8
root_interface_container=16
minimap_draw_area=21
fixed_viewport=32
multicombat_indicator=36
friends_chat_tab=46
ignores_tab=47
friends_tab=48
logout_tab=49
options_tab=50
emotes_tab=51
music_tab=52
friends_chat_icon=53
ignores_icon=54
friends_icon=55
logout_icon=56
options_icon=57
emotes_icon=58
music_icon=59
combat_tab=62
stats_tab=63
quests_tab=64
inventory_tab=65
equipment_tab=66
prayer_tab=67
magic_tab=68
combat_icon=69
stats_icon=70
quests_icon=71
inventory_icon=72
equipment_icon=73
prayer_icon=74
magic_icon=75
bank_container=77
interface_container=78
inventory_container=82

[fossil_island_oxygen_bar]
id=609
bar=1

[friend_list]
id=429
title=3
full_container=5
sort_by_name_button=7
sort_by_last_world_change_button=8
sort_by_world_button=9
legacy_sort_button=10
names_container=11
scroll_bar=12
loading_text=13
previous_name_holder=18

[friends_chat]
id=7
root=0
title=1
owner=2
list=12

[fullscreen_container_tli]
id=165

[gauntlet_timer]
id=637
container=2

[generic_scroll]
id=625
text=7

[gnomeball]
id=139
score=2

[gotr]
id=746
display=2

[grand_exchange]
id=465
window_container=0
offer_container=25
offer_description=26

[grand_exchange_inventory]
id=467
inventory_item_container=0

[gravestone]
id=672

[group_iron]
id=726

[group_storage]
id=724
ui=2
item_container=10

[group_storage_inventory]
id=725

[guide_prices]
id=464
inventory_item_container=0
item_container=2

[guide_prices_inventory]
id=238

[gwd_kc]
id=406
layer=5

[hallowed_sepulchre_timer]
id=668
container=2

[health]
id=303
healthbar_container=5
healthbar_text=20

[ignore_list]
id=432
title=3
full_container=5
sort_by_name_button=7
legacy_sort_button=8
names_container=9
scroll_bar=10
loading_text=11
previous_name_holder=16

[inventory]
id=149
container=0

[kept_on_death]
id=4

[kill_log]
id=549
title=3
monster=13
kills=14
streak=15

[kingdom]
id=616

[kourend_favour]
id=246
overlay=1

[level_up]
id=233
skill=1
level=2

[light_box]
id=322
light_box=1
light_box_window=2
light_bulb_container=3
button_a=8
button_b=9
button_c=10
button_d=11
button_e=12
button_f=13
button_g=14
button_h=15

[lms]
id=333
info=2

[lms_ingame]
id=328
info=4

[lms_kda]
id=333
info=4

[login_click_to_play_screen]
id=378
message_of_the_day=6

[logout_panel]
id=182
world_switcher_button=3
logout_button=6

[looting_bag]
id=81
looting_bag_inventory=5

[minigames]
id=160
teleport_button=30

[minimap]
id=160
container=0
xp_orb=5
health_orb=6
prayer_orb=17
quick_prayer_orb=19
prayer_orb_text=20
run_orb=25
toggle_run_orb=27
run_orb_text=28
spec_orb=33
worldmap_orb=48
wiki_banner_parent=49
wiki_banner=50
worldmap_options=53

[mlm]
id=382
container=0

[mortton_temple]
id=171
status=2

[mta_alchemy]
id=194
points=2

[mta_enchant]
id=195
points=2
bonus=8

[mta_graveyard]
id=196
points=2
values=8

[mta_telekinetic]
id=198
points=2
solved=8

[music]
id=239
container=0
scroll_container=4
list=6
scrollbar=7

[nightmare_pillar_health]
id=413
layer=1

[nmz]
id=202
container=0

[pest_control]
id=408
knight_info_container=2
activity_shield_container=9
activity_bar=10
activity_progress=12
purple_shield=13
blue_shield=14
yellow_shield=15
red_shield=16
purple_icon=17
blue_icon=18
yellow_icon=19
red_icon=20
purple_health=21
blue_health=22
yellow_health=23
red_health=24

[pest_control_boat]
id=407
layer=2

[poh_treasure_chest_inv]
id=674
container=0

[prayer]
id=541

[private_chat]
id=163

[puzzle_box]
id=306
visible_box=4

[pvp]
id=90
killdeath_ratio=26
wilderness_skull_container=44
skull_container=45
safe_zone=47
wilderness_level=50

[pyramid_plunder]
id=428
data=2

[quest_completed]
id=153
name_text=4

[quest_list]
id=399
box=0
container=2

[quick_prayer]
id=77
prayers=4

[raids]
id=513
points_infobox=3

[raiding_party]
id=500

[resizable_viewport]
id=161
resizable_viewport_old_school_box=15
multicombat_indicator=19
minimap_draw_area=29
minimap_orb_holder=32
friends_chat_tab=42
ignores_tab=43
friends_tab=44
logout_tab=45
options_tab=46
emotes_tab=47
music_tab=48
friends_chat_icon=49
ignores_icon=50
friends_icon=51
logout_icon=52
options_icon=53
emotes_icon=54
music_icon=55
combat_tab=58
stats_tab=59
quests_tab=60
inventory_tab=61
equipment_tab=62
prayer_tab=63
magic_tab=64
combat_icon=65
stats_icon=66
quests_icon=67
inventory_icon=68
equipment_icon=69
prayer_icon=70
magic_icon=71
interface_container=72
inventory_container=78
minimap=93
chatbox_parent=94
inventory_parent=95

[resizable_viewport_bottom_line]
id=164
resizable_viewport_bottom_line=15
multicombat_indicator=19
minimap_draw_area=29
minimap_orb_holder=32
logout_button_overlay=33
minimap_logout_button=34
fc_icon=43
friend_icon=45
settings_icon=46
emote_icon=47
music_icon=48
inventory_tab=54
prayer_tab=56
cmb_icon=58
skills_icon=59
quests_icon=60
inventory_icon=61
equip_icon=62
prayer_icon=63
magic_icon=64
interface_container=69
inventory_container=75
minimap=90
chatbox_parent=91
tabs1=92
tabs2=93
inventory_parent=94

[rune_pouch]
id=190

[sanity]
id=834
overlay=3

[seed_box]
id=128

[seed_vault]
id=631
inventory_item_container=1
title_container=2
item_container=15
item_text=16
search_button=24

[seed_vault_inventory]
id=630

[settings]
id=134
init=1

[settings_side]
id=116
camera_zoom_slider_track=57
music_slider=92
music_slider_step_holder=104
sound_effect_slider=106
area_sound_slider=120

[shop]
id=300
inventory_item_container=0

[shop_inventory]
id=301

[strangler]
id=836
overlay=4

[skills]
id=320
container=0

[skotizo]
id=308
container=2

[slayer_rewards]
id=426
top_bar=12

[smithing]
id=312
inventory_item_container=0

[spellbook]
id=218
kourend_home_teleport=4
catherby_home_teleport=5
lumbridge_home_teleport=6
edgeville_home_teleport=100
lunar_home_teleport=101
arceuus_home_teleport=145
fertile_soil=126

[tempoross]
id=437
status_indicator=2

[tempoross_lobby]
id=687
lobby=5

[tithe_farm]
id=241
layer=2

[toa_party]
id=773
layer=2

[toa_raid]
id=481
layer=3

[toa_reward]
id=771

[tob]
id=28
party_interface=5
party_stats=7
healthbar_container=9

[tob_reward]
id=23

[trade]
id=335
header=31

[trade_inventory]
id=336

[trailblazer_areas]
id=512
teleport=59

[trawler]
id=366
contribution=13
timer=14

[trawler_reward]
id=367

[trouble_brewing]
id=415
score=68

[trouble_brewing_lobby]
id=418
lobby=2

[varrock_museum]
id=533
question=28
first_answer=29
second_answer=30
third_answer=31

[volcanic_mine]
id=611
stability_infobox_container=2
time_left=6
points=8
stability=10
player_count=12
vent_a_percentage=16
vent_b_percentage=17
vent_c_percentage=18
vent_a_status=20
vent_b_status=21
vent_c_status=22
vents_infobox_container=26

[wilderness_loot_chest]
id=742

[world_map]
id=595
mapview=7
overview_map=10
bottom_bar=23
search=26
surface_selector=34
tooltip=41

[world_switcher]
id=69
world_list=18

[zeah_mess_hall]
id=235
cooking_display=2

