package dev.hoot.api.magic;

import net.runelite.api.widgets.WidgetInfo;

public enum Lunar implements Spell
{
	// Teleport spells
	LUNAR_HOME_TELEPORT(0, WidgetInfo.SPELL_LUNAR_HOME_TELEPORT),
	MOONCLAN_TELEPORT(69, WidgetInfo.SPELL_MOONCLAN_TELEPORT),
	TELE_GROUP_MOONCLAN(70, WidgetInfo.SPELL_TELE_GROUP_MOONCLAN),
	OURANIA_TELEPORT(71, WidgetInfo.SPELL_OURANIA_TELEPORT),
	WATERBIRTH_TELEPORT(72, WidgetInfo.SPELL_WATERBIRTH_TELEPORT),
	TELE_GROUP_WATERBIRTH(73, WidgetInfo.SPELL_TELE_GROUP_WATERBIRTH),
	BARBARIAN_TELEPORT(75, WidgetInfo.SPELL_BARBARIAN_TELEPORT),
	TELE_GROUP_BARBARIAN(76, WidgetInfo.SPELL_TELE_GROUP_BARBARIAN),
	KHAZARD_TELEPORT(78, WidgetInfo.SPELL_KHAZARD_TELEPORT),
	TELE_GROUP_KHAZARD(79, WidgetInfo.SPELL_TELE_GROUP_KHAZARD),
	FISHING_GUILD_TELEPORT(85, WidgetInfo.SPELL_FISHING_GUILD_TELEPORT),
	TELE_GROUP_FISHING_GUILD(86, WidgetInfo.SPELL_TELE_GROUP_FISHING_GUILD),
	CATHERBY_TELEPORT(87, WidgetInfo.SPELL_CATHERBY_TELEPORT),
	TELE_GROUP_CATHERBY(88, WidgetInfo.SPELL_TELE_GROUP_CATHERBY),
	ICE_PLATEAU_TELEPORT(89, WidgetInfo.SPELL_ICE_PLATEAU_TELEPORT),
	TELE_GROUP_ICE_PLATEAU(90, WidgetInfo.SPELL_TELE_GROUP_ICE_PLATEAU),

	// Combat spells
	MONSTER_EXAMINE(66, WidgetInfo.SPELL_MONSTER_EXAMINE),
	CURE_OTHER(66, WidgetInfo.SPELL_CURE_OTHER),
	CURE_ME(66, WidgetInfo.SPELL_CURE_ME),
	CURE_GROUP(66, WidgetInfo.SPELL_CURE_GROUP),
	STAT_SPY(66, WidgetInfo.SPELL_STAT_SPY),
	DREAM(66, WidgetInfo.SPELL_DREAM),
	STAT_RESTORE_POT_SHARE(66, WidgetInfo.SPELL_STAT_RESTORE_POT_SHARE),
	BOOST_POTION_SHARE(66, WidgetInfo.SPELL_BOOST_POTION_SHARE),
	ENERGY_TRANSFER(66, WidgetInfo.SPELL_ENERGY_TRANSFER),
	HEAL_OTHER(66, WidgetInfo.SPELL_HEAL_OTHER),
	VENGEANCE_OTHER(66, WidgetInfo.SPELL_VENGEANCE_OTHER),
	VENGEANCE(66, WidgetInfo.SPELL_VENGEANCE),
	HEAL_GROUP(66, WidgetInfo.SPELL_HEAL_GROUP),

	// Utility spells
	BAKE_PIE(66, WidgetInfo.SPELL_BAKE_PIE),
	GEOMANCY(66, WidgetInfo.SPELL_GEOMANCY),
	CURE_PLANT(66, WidgetInfo.SPELL_CURE_PLANT),
	NPC_CONTACT(66, WidgetInfo.SPELL_NPC_CONTACT),
	HUMIDIFY(66, WidgetInfo.SPELL_HUMIDIFY),
	HUNTER_KIT(66, WidgetInfo.SPELL_HUNTER_KIT),
	SPIN_FLAX(66, WidgetInfo.SPELL_SPIN_FLAX),
	SUPERGLASS_MAKE(66, WidgetInfo.SPELL_SUPERGLASS_MAKE),
	TAN_LEATHER(66, WidgetInfo.SPELL_TAN_LEATHER),
	STRING_JEWELLERY(66, WidgetInfo.SPELL_STRING_JEWELLERY),
	MAGIC_IMBUE(66, WidgetInfo.SPELL_MAGIC_IMBUE),
	FERTILE_SOIL(66, WidgetInfo.SPELL_FERTILE_SOIL),
	PLANK_MAKE(66, WidgetInfo.SPELL_PLANK_MAKE),
	RECHARGE_DRAGONSTONE(66, WidgetInfo.SPELL_RECHARGE_DRAGONSTONE),
	SPELLBOOK_SWAP(66, WidgetInfo.SPELL_SPELLBOOK_SWAP),

	;

	private final int level;
	private final WidgetInfo widgetInfo;

	Lunar(int level, WidgetInfo widgetInfo)
	{
		this.level = level;
		this.widgetInfo = widgetInfo;
	}

	@Override
	public int getLevel()
	{
		return level;
	}

	@Override
	public WidgetInfo getWidget()
	{
		return widgetInfo;
	}
}
