package dev.hoot.api.magic;

import net.runelite.api.widgets.WidgetInfo;

public enum Necromancy implements Spell
{
	// Teleport spells
	ARCEUUS_HOME_TELEPORT(1, WidgetInfo.SPELL_ARCEUUS_HOME_TELEPORT),
	ARCEUUS_LIBRARY_TELEPORT(6, WidgetInfo.SPELL_ARCEUUS_LIBRARY_TELEPORT),
	DRAYNOR_MANOR_TELEPORT(17, WidgetInfo.SPELL_DRAYNOR_MANOR_TELEPORT),
	BATTLEFRONT_TELEPORT(23, WidgetInfo.SPELL_BATTLEFRONT_TELEPORT),
	MIND_ALTAR_TELEPORT(28, WidgetInfo.SPELL_MIND_ALTAR_TELEPORT),
	RESPAWN_TELEPORT(34, WidgetInfo.SPELL_RESPAWN_TELEPORT),
	SALVE_GRAVEYARD_TELEPORT(40, WidgetInfo.SPELL_SALVE_GRAVEYARD_TELEPORT),
	FENKENSTRAINS_CASTLE_TELEPORT(48, WidgetInfo.SPELL_FENKENSTRAINS_CASTLE_TELEPORT),
	WEST_ARDOUGNE_TELEPORT(61, WidgetInfo.SPELL_WEST_ARDOUGNE_TELEPORT),
	HARMONY_ISLAND_TELEPORT(65, WidgetInfo.SPELL_HARMONY_ISLAND_TELEPORT),
	CEMETERY_TELEPORT(71, WidgetInfo.SPELL_CEMETERY_TELEPORT),
	BARROWS_TELEPORT(83, WidgetInfo.SPELL_BARROWS_TELEPORT),
	APE_ATOLL_TELEPORT(90, WidgetInfo.SPELL_APE_ATOLL_TELEPORT),

	// Combat spells
	GHOSTLY_GRASP(35, WidgetInfo.SPELL_GHOSTLY_GRASP),
	SKELETAL_GRASP(56, WidgetInfo.SPELL_SKELETAL_GRASP),
	UNDEAD_GRASP(79, WidgetInfo.SPELL_UNDEAD_GRASP),
	INFERIOR_DEMONBANE(44, WidgetInfo.SPELL_INFERIOR_DEMONBANE),
	SUPERIOR_DEMONBANE(62, WidgetInfo.SPELL_SUPERIOR_DEMONBANE),
	DARK_DEMONBANE(82, WidgetInfo.SPELL_DARK_DEMONBANE),
	LESSER_CORRUPTION(64, WidgetInfo.SPELL_LESSER_CORRUPTION),
	GREATER_CORRUPTION(85, WidgetInfo.SPELL_GREATER_CORRUPTION),
	RESURRECT_LESSER_GHOST(38, WidgetInfo.SPELL_RESURRECT_LESSER_GHOST),
	RESURRECT_LESSER_SKELETON(38, WidgetInfo.SPELL_RESURRECT_LESSER_SKELETON),
	RESURRECT_LESSER_ZOMBIE(38, WidgetInfo.SPELL_RESURRECT_LESSER_ZOMBIE),
	RESURRECT_SUPERIOR_GHOST(57, WidgetInfo.SPELL_RESURRECT_SUPERIOR_GHOST),
	RESURRECT_SUPERIOR_SKELETON(57, WidgetInfo.SPELL_RESURRECT_SUPERIOR_SKELETON),
	RESURRECT_SUPERIOR_ZOMBIE(57, WidgetInfo.SPELL_RESURRECT_SUPERIOR_ZOMBIE),
	RESURRECT_GREATER_GHOST(76, WidgetInfo.SPELL_RESURRECT_GREATER_GHOST),
	RESURRECT_GREATER_SKELETON(76, WidgetInfo.SPELL_RESURRECT_GREATER_SKELETON),
	RESURRECT_GREATER_ZOMBIE(76, WidgetInfo.SPELL_RESURRECT_GREATER_ZOMBIE),
	DARK_LURE(50, WidgetInfo.SPELL_DARK_LURE),
	MARK_OF_DARKNESS(59, WidgetInfo.SPELL_MARK_OF_DARKNESS),
	WARD_OF_ARCEUUS(73, WidgetInfo.SPELL_WARD_OF_ARCEUUS),

	// Utility spells
	BASIC_REANIMATION(16, WidgetInfo.SPELL_BASIC_REANIMATION),
	ADEPT_REANIMATION(41, WidgetInfo.SPELL_ADEPT_REANIMATION),
	EXPERT_REANIMATION(72, WidgetInfo.SPELL_EXPERT_REANIMATION),
	MASTER_REANIMATION(90, WidgetInfo.SPELL_MASTER_REANIMATION),
	DEMONIC_OFFERING(84, WidgetInfo.SPELL_DEMONIC_OFFERING),
	SINISTER_OFFERING(92, WidgetInfo.SPELL_SINISTER_OFFERING),
	SHADOW_VEIL(47, WidgetInfo.SPELL_SHADOW_VEIL),
	VILE_VIGOUR(66, WidgetInfo.SPELL_VILE_VIGOUR),
	DEGRIME(70, WidgetInfo.SPELL_DEGRIME),
	RESURRECT_CROPS(78, WidgetInfo.SPELL_RESURRECT_CROPS),
	DEATH_CHARGE(80, WidgetInfo.SPELL_DEATH_CHARGE),

	;

	private final int level;
	private final WidgetInfo widgetInfo;

	Necromancy(int level, WidgetInfo widgetInfo)
	{
		this.level = level;
		this.widgetInfo = widgetInfo;
	}

	@Override
	public int getLevel()
	{
		return level;
	}

	@Override
	public WidgetInfo getWidget()
	{
		return widgetInfo;
	}
}
